# Generated by Django 5.1.1 on 2026-06-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى'), ('refunded', 'مسترد')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى'), ('refunded', 'مسترد')], max_length=20),
        ),
    ]
