# Generated by Django 5.1.1 on 2026-06-01 21:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_product_options_and_more'),
        ('orders', '0002_alter_order_status_alter_orderlog_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'كوبون', 'verbose_name_plural': 'الكوبونات'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'بند طلب', 'verbose_name_plural': 'بنود الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderlog',
            options={'ordering': ['created_at'], 'verbose_name': 'سجل طلب', 'verbose_name_plural': 'سجلات الطلبات'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='خصم (%)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=0, verbose_name='أقصى عدد استخدام'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تم استخدامه'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=40, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ الإجمالي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='ملاحظات المدير'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon', verbose_name='الكوبون'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfillment_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات التنفيذ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='رقم الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'في انتظار الدفع'), ('paid', 'مدفوع'), ('processing', 'قيد المعالجة'), ('delivered', 'تم التسليم'), ('completed', 'مكتمل'), ('refunded', 'مسترد'), ('cancelled', 'ملغى'), ('disputed', 'متنازع عليه')], default='pending_payment', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي المبلغ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='السعر الإجمالي'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='الباقة'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='من قبل'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='note',
            field=models.TextField(blank=True, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'في انتظار الدفع'), ('paid', 'مدفوع'), ('processing', 'قيد المعالجة'), ('delivered', 'تم التسليم'), ('completed', 'مكتمل'), ('refunded', 'مسترد'), ('cancelled', 'ملغى'), ('disputed', 'متنازع عليه')], max_length=20, verbose_name='الحالة'),
        ),
    ]
