# Generated by Django 5.1.1 on 2026-06-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_coupon_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('refunded', 'مسترد'), ('cancelled', 'ملغى'), ('disputed', 'متنازع عليه')], default='processing', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='status',
            field=models.CharField(choices=[('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('refunded', 'مسترد'), ('cancelled', 'ملغى'), ('disputed', 'متنازع عليه')], max_length=20, verbose_name='الحالة'),
        ),
    ]
