# Generated by Django 5.1.1 on 2026-06-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivery_read',
            field=models.BooleanField(default=False, verbose_name='تمت رؤية المنتج الرقمي'),
        ),
    ]
