# Generated by Django 5.1.1 on 2026-06-10 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_category_icon'),
        ('orders', '0007_order_is_delivery_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='apply_to_all_products',
            field=models.BooleanField(default=True, verbose_name='يعمل على جميع المنتجات'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_verified_only',
            field=models.BooleanField(default=True, verbose_name='للحسابات الموثقة فقط'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_to_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='محدد لمنتج معين'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=1, verbose_name='أقصى عدد استخدام لكل مستخدم'),
        ),
        migrations.AddField(
            model_name='order',
            name='original_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المبلغ الأصلي قبل التعديل'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_adjustment_reason',
            field=models.TextField(blank=True, verbose_name='سبب تعديل السعر'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=0, verbose_name='أقصى عدد استخدام لجميع المستخدمين (0 = غير محدود)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي عدد المرات التي تم استخدامه'),
        ),
    ]
