# Generated by Django 5.1.1 on 2026-06-10 22:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_coupon_apply_to_all_products_coupon_is_verified_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='خصم بمبلغ ثابت (USD)'),
        ),
    ]
