# Generated by Django 5.1.1 on 2026-06-10 23:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_coupon_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'نسبة مئوية (%)'), ('fixed_amount', 'مبلغ ثابت (USD)')], default='percentage', max_length=20, verbose_name='نوع الخصم'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='قيمة الخصم (USD)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='قيمة الخصم (%)'),
        ),
    ]
