# Generated by Django 5.1.1 on 2026-06-12 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_coupon_discount_type_alter_coupon_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limit_to_area',
            field=models.CharField(blank=True, max_length=255, verbose_name='محدد لمنطقة معينة (كلمة دلالية في العنوان)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_to_tiers',
            field=models.JSONField(blank=True, default=list, verbose_name='محدد لفئات معينة (Tiers)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_to_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='محدد لعملاء معينين'),
        ),
    ]
