# Generated by Django 5.1.1 on 2026-06-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_coupon_limit_to_area_coupon_limit_to_tiers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='allow_area_type',
            field=models.CharField(choices=[('residence', 'مكان الإقامة الحالي'), ('birth', 'مكان الولادة'), ('both', 'كلاهما')], default='residence', max_length=20, verbose_name='نوع المطابقة الجغرافية'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_to_place_of_birth',
            field=models.CharField(blank=True, max_length=255, verbose_name='محدد لمحل الولادة (كلمة دلالية)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limit_to_area',
            field=models.CharField(blank=True, max_length=255, verbose_name='محدد لمنطقة معينة (كلمة دلالية)'),
        ),
    ]
