# Generated by Django 5.1.1 on 2026-06-13 22:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_coupon_allow_area_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الحد الأدنى للطلب (USD)'),
        ),
    ]
