# Generated by Django 5.1.1 on 2026-06-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_coupon_min_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limit_to_ip_cities',
            field=models.JSONField(blank=True, default=list, verbose_name='محدد لمدن/مناطق معينة (IP-based)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_to_ip_countries',
            field=models.JSONField(blank=True, default=list, verbose_name='محدد لدول معينة (IP-based)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='match_mode',
            field=models.CharField(choices=[('all', 'يجب تحقق جميع الشروط (AND)'), ('any', 'يكفي تحقق أي شرط واحد (OR)')], default='all', max_length=10, verbose_name='طريقة المطابقة'),
        ),
    ]
