# Generated by Django 5.1.1 on 2026-06-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productvariant_is_temporarily_disabled'),
        ('orders', '0014_coupon_limit_to_ip_cities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='limit_to_product',
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_to_products',
            field=models.ManyToManyField(blank=True, to='catalog.product', verbose_name='محدد لمنتجات معينة'),
        ),
    ]
