# Generated by Django 5.1.1 on 2026-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_multi_product_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_for_users_before',
            field=models.DateTimeField(blank=True, null=True, verbose_name='صالح للحسابات المسجلة قبل تاريخ'),
        ),
    ]
