# Generated by Django 5.1.1 on 2026-06-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_coupon_valid_for_users_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_for_users_after',
            field=models.DateTimeField(blank=True, null=True, verbose_name='صالح للحسابات المسجلة بعد تاريخ'),
        ),
    ]
