# Generated by Django 5.1.1 on 2026-06-19 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_coupon_valid_for_users_after'),
        ('stores', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='stores.store', verbose_name='المتجر'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store', verbose_name='المتجر'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=40, verbose_name='الكود'),
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('store', 'code')},
        ),
    ]
