# Generated by Django 5.1.1 on 2026-06-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_coupon_store_order_store_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='عنوان الشحن'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, max_length=100, verbose_name='شركة الشحن'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم المستلم'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='رقم هاتف الشحن'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم التتبع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'قيد المعالجة'), ('shipped', 'قيد الشحن'), ('delivered', 'مسلّم'), ('returned', 'مرتجع'), ('completed', 'مكتمل'), ('refunded', 'مسترد'), ('cancelled', 'ملغى'), ('disputed', 'متنازع عليه')], default='processing', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='status',
            field=models.CharField(choices=[('processing', 'قيد المعالجة'), ('shipped', 'قيد الشحن'), ('delivered', 'مسلّم'), ('returned', 'مرتجع'), ('completed', 'مكتمل'), ('refunded', 'مسترد'), ('cancelled', 'ملغى'), ('disputed', 'متنازع عليه')], max_length=20, verbose_name='الحالة'),
        ),
    ]
