# Generated by Django 5.1.1 on 2026-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_shipping_address_order_shipping_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='api_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الطلب في Alkasr'),
        ),
        migrations.AddField(
            model_name='order',
            name='api_order_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID الطلب في Alkasr'),
        ),
    ]
