# Generated by Django 5.1.1 on 2026-09-04 18:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18, verbose_name='تكلفة الوحدة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=8, max_digits=18, verbose_name='سعر الوحدة'),
        ),
    ]
