# Generated by Django 5.1.1 on 2026-06-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدير عام'), ('admin', 'مدير'), ('moderator', 'مشرف'), ('finance', 'مالية'), ('support', 'دعم'), ('employee', 'موظف'), ('customer', 'عميل')], default='customer', max_length=32),
        ),
    ]
