# Generated by Django 5.1.1 on 2026-06-01 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100, verbose_name='الإجراء')),
                ('previous_state', models.JSONField(blank=True, default=dict, verbose_name='الحالة السابقة')),
                ('new_state', models.JSONField(blank=True, default=dict, verbose_name='الحالة الجديدة')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('internal_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
            ],
            options={
                'verbose_name': 'سجل إشراف',
                'verbose_name_plural': 'سجلات الإشراف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AddField(
            model_name='user',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المشرف (داخلية)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_permanently_suspended',
            field=models.BooleanField(default=False, verbose_name='إيقاف نهائي'),
        ),
        migrations.AddField(
            model_name='user',
            name='restriction_deposits',
            field=models.BooleanField(default=False, verbose_name='تقييد الإيداع'),
        ),
        migrations.AddField(
            model_name='user',
            name='restriction_purchases',
            field=models.BooleanField(default=False, verbose_name='تقييد الشراء'),
        ),
        migrations.AddField(
            model_name='user',
            name='restriction_withdrawals',
            field=models.BooleanField(default=False, verbose_name='تقييد السحب'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف مؤقتاً'), ('frozen', 'مجمد'), ('restricted', 'مقيد'), ('under_review', 'قيد المراجعة'), ('banned', 'محظور نهائياً')], default='active', max_length=32, verbose_name='حالة الحساب'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الإيقاف'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, verbose_name='سبب الإيقاف (للمستخدم)'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='accounts_us_status_6bbe13_idx'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_moderations', to=settings.AUTH_USER_MODEL, verbose_name='المشرف'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستهدف'),
        ),
    ]
