# Generated by Django 5.1.1 on 2026-06-05 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_public_uuid_safe'),
        ('common', '0003_remove_currency_exchange_rate_currency_buy_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency', verbose_name='العملة المفضلة'),
        ),
    ]
