# Generated by Django 5.1.1 on 2026-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_preferred_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدير عام'), ('admin', 'مدير'), ('moderator', 'مشرف'), ('finance', 'مالية'), ('support', 'دعم'), ('employee', 'موظف'), ('verified_merchant', 'تاجر معتمد'), ('customer', 'عميل')], default='customer', max_length=32),
        ),
    ]
