# Generated by Django 5.1.1 on 2026-06-06 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_otptoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تم التوثيق'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('id_number', models.CharField(max_length=50, verbose_name='رقم الهوية')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('father_name', models.CharField(max_length=100, verbose_name='اسم الأب')),
                ('last_name', models.CharField(max_length=100, verbose_name='النسبة / الكنية')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('place_of_birth', models.CharField(max_length=255, verbose_name='مكان الميلاد')),
                ('current_residence', models.TextField(verbose_name='عنوان الإقامة الحالي')),
                ('document_type', models.CharField(choices=[('id', 'الهوية الوطنية'), ('passport', 'جواز السفر'), ('license', 'رخصة القيادة')], max_length=20, verbose_name='نوع الوثيقة')),
                ('identity_front', models.ImageField(upload_to='kyc/front/', verbose_name='وجه الوثيقة')),
                ('identity_back', models.ImageField(upload_to='kyc/back/', verbose_name='ظهر الوثيقة')),
                ('selfie_verification', models.ImageField(upload_to='kyc/selfie/', verbose_name='صورة سيلفي مع الوثيقة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kycs', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب توثيق هوية',
                'verbose_name_plural': 'طلبات توثيق الهوية',
            },
        ),
    ]
