# Generated by Django 5.1.1 on 2026-06-06 19:34

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_kycrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_deposit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14, verbose_name='حد الإيداع اليومي'),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_deposit_usage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14, verbose_name='حد السحب اليومي'),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_withdrawal_usage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='is_kyc_verified',
            field=models.BooleanField(default=False, verbose_name='موثق الهوية'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_limit_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
