# Generated by Django 5.1.1 on 2026-06-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_daily_deposit_limit_user_daily_deposit_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrequest',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='mother_name',
            field=models.CharField(default='', max_length=255, verbose_name='اسم الأم بالكامل'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='id_number',
            field=models.CharField(max_length=50, verbose_name='رقم الهوية / الوثيقة'),
        ),
    ]
