# Generated by Django 5.1.1 on 2026-06-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_kycrequest_gender_kycrequest_mother_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_custom_limits',
            field=models.BooleanField(default=False, verbose_name='له حدود مخصصة'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='id_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الهوية / الوثيقة'),
        ),
    ]
