# Generated by Django 5.1.1 on 2026-06-06 20:35

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_has_custom_limits_alter_kycrequest_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unverified_daily_deposit_limit', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14, verbose_name='حد إيداع غير الموثقين')),
                ('unverified_daily_withdrawal_limit', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14, verbose_name='حد سحب غير الموثقين')),
                ('verified_daily_deposit_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=14, verbose_name='حد إيداع الموثقين')),
                ('verified_daily_withdrawal_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=14, verbose_name='حد سحب الموثقين')),
                ('restricted_countries', models.JSONField(blank=True, default=list, verbose_name='الدول المحظورة (قائمة أسماء أو رموز)')),
                ('block_by_nationality', models.BooleanField(default=True, verbose_name='حظر حسب الجنسية')),
                ('block_by_issuing_country', models.BooleanField(default=True, verbose_name='حظر حسب بلد إصدار الوثيقة')),
            ],
            options={
                'verbose_name': 'إعدادات التوثيق والحدود',
                'verbose_name_plural': 'إعدادات التوثيق والحدود',
            },
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='issuing_country',
            field=models.CharField(default='', max_length=100, verbose_name='بلد إصدار الوثيقة'),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='nationality',
            field=models.CharField(default='', max_length=100, verbose_name='الجنسية'),
        ),
    ]
