# Generated by Django 5.1.1 on 2026-06-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_kycsettings_kycrequest_issuing_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrequest',
            name='issuing_country',
            field=models.CharField(max_length=100, verbose_name='بلد إصدار الوثيقة'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='nationality',
            field=models.CharField(max_length=100, verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='kycsettings',
            name='restricted_countries',
            field=models.JSONField(blank=True, default=list, verbose_name='الدول المحظورة'),
        ),
    ]
