# Generated by Django 5.1.1 on 2026-06-06 20:50

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_kycsettings_kycrequest_issuing_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrequest',
            name='issuing_country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='بلد إصدار الوثيقة'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='kycsettings',
            name='restricted_countries',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True, verbose_name='الدول المحظورة'),
        ),
    ]
