# Generated by Django 5.1.1 on 2026-06-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_custom_payment_limits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('customer', 'عميل'), ('dealer', 'تاجر معتمد'), ('vip', 'VIP')], default='customer', max_length=20, verbose_name='الفئة'),
        ),
    ]
