# Generated by Django 5.1.1 on 2026-06-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='ar', max_length=10, verbose_name='اللغة المفضلة'),
        ),
    ]
