# Generated by Django 5.1.1 on 2026-06-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
