# Generated by Django 5.1.1 on 2026-06-10 21:08

import django.contrib.auth.models
import django.contrib.auth.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_last_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryKYCImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('image_type', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('selfie', 'Selfie')], max_length=20)),
                ('file', models.ImageField(upload_to='kyc/temp/')),
            ],
            options={
                'verbose_name': 'صورة توثيق مؤقتة',
                'verbose_name_plural': 'صور توثيق مؤقتة',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_email_74c8d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_role_1fa9a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_status_6bbe13_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_tier_dfefa5_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='custom_payment_limits',
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المدير'),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_deposit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'عميل'), ('support', 'دعم فني'), ('finance', 'محاسب'), ('admin', 'مدير')], default='customer', max_length=20, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('banned', 'محظور')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, verbose_name='سبب الإيقاف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('standard', 'عادي'), ('wholesale', 'جملة'), ('vip', 'VIP')], default='standard', max_length=20, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
