# Generated by Django 5.1.1 on 2026-06-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_last_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsettings',
            name='otp_base_cooldown',
            field=models.IntegerField(default=60, verbose_name='المدة الأساسية لانتظار الرمز (بالثواني)'),
        ),
        migrations.AddField(
            model_name='kycsettings',
            name='otp_max_attempts',
            field=models.IntegerField(default=5, verbose_name='الحد الأقصى لمحاولات الرمز الخاطئ'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
