# Generated by Django 5.1.1 on 2026-06-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_totp_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='require_otp_on_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='require_otp_on_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='require_otp_on_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
