# Generated by Django 5.1.1 on 2026-06-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_require_otp_on_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_deposit_method',
            field=models.CharField(choices=[('NONE', 'معطل'), ('EMAIL', 'البريد الإلكتروني فقط'), ('APP', 'تطبيق المصادقة (2FA) فقط'), ('BOTH', 'البريد الإلكتروني + تطبيق المصادقة')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='security_login_method',
            field=models.CharField(choices=[('NONE', 'معطل'), ('EMAIL', 'البريد الإلكتروني فقط'), ('APP', 'تطبيق المصادقة (2FA) فقط'), ('BOTH', 'البريد الإلكتروني + تطبيق المصادقة')], default='EMAIL', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='security_purchase_method',
            field=models.CharField(choices=[('NONE', 'معطل'), ('EMAIL', 'البريد الإلكتروني فقط'), ('APP', 'تطبيق المصادقة (2FA) فقط'), ('BOTH', 'البريد الإلكتروني + تطبيق المصادقة')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='security_withdraw_method',
            field=models.CharField(choices=[('NONE', 'معطل'), ('EMAIL', 'البريد الإلكتروني فقط'), ('APP', 'تطبيق المصادقة (2FA) فقط'), ('BOTH', 'البريد الإلكتروني + تطبيق المصادقة')], default='NONE', max_length=10),
        ),
    ]
