# Generated by Django 5.1.1 on 2026-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_security_deposit_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='كلمة مرور الحماية'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_password_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل حماية الإعدادات'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset'), ('deposit', 'Deposit'), ('purchase', 'Purchase'), ('withdraw', 'Withdraw'), ('email_change', 'Email Change')], max_length=20),
        ),
    ]
