# Generated by Django 5.1.1 on 2026-06-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_security_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_deposit_method',
            field=models.CharField(choices=[('NONE', 'معطل'), ('EMAIL', 'البريد الإلكتروني فقط'), ('APP', 'تطبيق المصادقة (2FA) فقط'), ('BOTH', 'البريد الإلكتروني وتطبيق المصادقة معاً'), ('SP', 'كلمة مرور الحماية')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_login_method',
            field=models.CharField(choices=[('NONE', 'معطل'), ('EMAIL', 'البريد الإلكتروني فقط'), ('APP', 'تطبيق المصادقة (2FA) فقط'), ('BOTH', 'البريد الإلكتروني وتطبيق المصادقة معاً'), ('SP', 'كلمة مرور الحماية')], default='EMAIL', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_purchase_method',
            field=models.CharField(choices=[('NONE', 'معطل'), ('EMAIL', 'البريد الإلكتروني فقط'), ('APP', 'تطبيق المصادقة (2FA) فقط'), ('BOTH', 'البريد الإلكتروني وتطبيق المصادقة معاً'), ('SP', 'كلمة مرور الحماية')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_withdraw_method',
            field=models.CharField(choices=[('NONE', 'معطل'), ('EMAIL', 'البريد الإلكتروني فقط'), ('APP', 'تطبيق المصادقة (2FA) فقط'), ('BOTH', 'البريد الإلكتروني وتطبيق المصادقة معاً'), ('SP', 'كلمة مرور الحماية')], default='NONE', max_length=10),
        ),
    ]
