# Generated by Django 5.1.1 on 2026-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_user_security_deposit_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='آخر مدينة'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='آخر دولة'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر عنوان IP'),
        ),
    ]
