# Generated by Django 5.1.1 on 2026-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_user_last_city_user_last_country_user_last_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
