# Generated by Django 5.1.1 on 2026-06-16 22:46

from django.db import migrations, models

def clean_empty_phones(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # This must run AFTER the column is made nullable in the database
    User.objects.filter(phone='').update(phone=None)

def fix_postgres_unique_constraint(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    # Standard Django constraint and index names for this field in Postgres
    constraint_name = "accounts_user_phone_c603acdd_uniq"
    like_index_name = "accounts_user_phone_c603acdd_like"
    
    with schema_editor.connection.cursor() as cursor:
        # 1. Drop the unique constraint if it exists
        cursor.execute(f"ALTER TABLE accounts_user DROP CONSTRAINT IF EXISTS {constraint_name};")
        
        # 2. Drop the "LIKE" index if it exists (causes ProgrammingError: relation ... already exists)
        cursor.execute(f"DROP INDEX IF EXISTS {like_index_name};")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_securityevent_city_securityevent_country'),
    ]

    operations = [
        # 1. For Postgres, drop problematic constraints and indexes first
        migrations.RunPython(fix_postgres_unique_constraint, reverse_code=migrations.RunPython.noop),
        
        # 2. Make the field nullable (State and DB)
        # Note: We temporarily remove unique=True to allow data cleanup
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        
        # 3. Clean up data (now that it's nullable)
        migrations.RunPython(clean_empty_phones, reverse_code=migrations.RunPython.noop),
        
        # 4. Now re-add the unique constraint
        # Django will recreate the constraint and the _like index
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
