# Generated by Django 5.1.1 on 2026-06-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_securityevent_city_securityevent_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
