# Generated by Django 5.1.1 on 2026-06-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_full_name',
            field=models.BooleanField(default=False, verbose_name='عرض الاسم الكامل'),
        ),
    ]
