# Generated by Django 5.1.1 on 2026-06-18 13:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_user_show_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsettings',
            name='p2p_transfer_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل التحويل بين المستخدمين'),
        ),
        migrations.AddField(
            model_name='kycsettings',
            name='require_kyc_for_transfer',
            field=models.BooleanField(default=False, verbose_name='اشتراط التوثيق للتحويل'),
        ),
        migrations.AddField(
            model_name='kycsettings',
            name='transfer_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة رسوم التحويل (%)'),
        ),
        migrations.AddField(
            model_name='kycsettings',
            name='unverified_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=14, verbose_name='حد التحويل لغير الموثقين'),
        ),
        migrations.AddField(
            model_name='kycsettings',
            name='verified_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=14, verbose_name='حد التحويل للموثقين'),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='المعرف الرقمي (UID)'),
        ),
    ]
