# Generated by Django 5.1.1 on 2026-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_kycsettings_p2p_transfer_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_p2p_transfer_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='حد تحويل P2P المخصص'),
        ),
    ]
