# Generated by Django 5.1.1 on 2026-06-19 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_user_custom_p2p_transfer_limit'),
        ('stores', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='stores.store', verbose_name='المتجر'),
        ),
    ]
