# Generated by Django 5.1.1 on 2026-06-19 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_store'),
        ('stores', '0002_saasadminrole_saasglobalsetting_storetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saas_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='stores.saasadminrole', verbose_name='الدور الإداري SaaS'),
        ),
    ]
