# Generated by Django 5.1.1 on 2026-06-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_user_saas_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0014_currency_store_alter_currency_code_and_more'),
        ('stores', '0007_store_button_style_store_custom_css_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('store__isnull', False)), fields=('email', 'store'), name='unique_email_per_store'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('store__isnull', True)), fields=('email',), name='unique_email_main_platform'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('store__isnull', False)), fields=('phone', 'store'), name='unique_phone_per_store'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('store__isnull', True)), fields=('phone',), name='unique_phone_main_platform'),
        ),
    ]
