# Generated by Django 5.1.1 on 2026-06-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_user_email_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsettings',
            name='require_kyc_for_store_creation',
            field=models.BooleanField(default=False, verbose_name='اشتراط التوثيق لإنشاء متجر'),
        ),
    ]
