# Generated by Django 5.1.1 on 2026-09-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_kycsettings_require_kyc_for_store_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('customer', 'عميل'), ('dealer', 'تاجر معتمد'), ('vip', 'VIP'), ('cost', 'سعر التكلفة')], default='customer', max_length=20, verbose_name='الفئة'),
        ),
    ]
