# Generated by Django 5.1.1 on 2026-09-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_user_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrequest',
            name='current_residence',
            field=models.TextField(blank=True, default='', verbose_name='عنوان الإقامة الحالي'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='document_type',
            field=models.CharField(blank=True, choices=[('id', 'الهوية الوطنية'), ('passport', 'جواز السفر'), ('license', 'رخصة القيادة')], default='id', max_length=20, verbose_name='نوع الوثيقة'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='اسم الأب'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الهوية / الوثيقة'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='identity_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/back/', verbose_name='ظهر الوثيقة'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='identity_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/front/', verbose_name='وجه الوثيقة'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='issuing_country',
            field=models.CharField(blank=True, choices=[('SY', 'سوريا'), ('TR', 'تركيا'), ('AE', 'الإمارات العربية المتحدة'), ('SA', 'المملكة العربية السعودية'), ('JO', 'الأردن'), ('LB', 'لبنان'), ('IQ', 'العراق'), ('EG', 'مصر'), ('KW', 'الكويت'), ('QA', 'قطر'), ('OM', 'عمان'), ('BH', 'البحرين'), ('YE', 'اليمن'), ('PS', 'فلسطين'), ('LY', 'ليبيا'), ('TN', 'تونس'), ('DZ', 'الجزائر'), ('MA', 'المغرب'), ('SD', 'السودان'), ('MR', 'موريتانيا'), ('SO', 'الصومال'), ('DJ', 'جيبوتي'), ('KM', 'جزر القمر'), ('US', 'الولايات المتحدة'), ('GB', 'المملكة المتحدة'), ('DE', 'ألمانيا'), ('FR', 'فرنسا'), ('CA', 'كندا'), ('AU', 'أستراليا'), ('CN', 'الصين'), ('JP', 'اليابان'), ('RU', 'روسيا'), ('IT', 'إيطاليا'), ('ES', 'إسبانيا'), ('CH', 'سويسرا'), ('NL', 'هولندا'), ('BE', 'بلجيكا'), ('SE', 'السويد'), ('NO', 'النرويج'), ('FI', 'فنلندا'), ('DK', 'الدنمارك'), ('AT', 'النمسا'), ('GR', 'اليونان'), ('CY', 'قبرص'), ('MY', 'ماليزيا'), ('ID', 'إندونيسيا'), ('IN', 'الهند'), ('PK', 'باكستان'), ('AF', 'أفغانستان'), ('IR', 'إيران'), ('AZ', 'أذربيجان'), ('GE', 'جورجيا'), ('UA', 'أوكرانيا'), ('PL', 'بولندا'), ('RO', 'رومانيا'), ('CZ', 'تشيكيا'), ('HU', 'المجر'), ('BR', 'البرازيل'), ('AR', 'الأرجنتين'), ('MX', 'المكسيك'), ('NG', 'نيجيريا'), ('ZA', 'جنوب أفريقيا')], default='', max_length=2, verbose_name='بلد إصدار الوثيقة'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='النسبة / الكنية'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الأم بالكامل'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='nationality',
            field=models.CharField(blank=True, choices=[('SY', 'سوريا'), ('TR', 'تركيا'), ('AE', 'الإمارات العربية المتحدة'), ('SA', 'المملكة العربية السعودية'), ('JO', 'الأردن'), ('LB', 'لبنان'), ('IQ', 'العراق'), ('EG', 'مصر'), ('KW', 'الكويت'), ('QA', 'قطر'), ('OM', 'عمان'), ('BH', 'البحرين'), ('YE', 'اليمن'), ('PS', 'فلسطين'), ('LY', 'ليبيا'), ('TN', 'تونس'), ('DZ', 'الجزائر'), ('MA', 'المغرب'), ('SD', 'السودان'), ('MR', 'موريتانيا'), ('SO', 'الصومال'), ('DJ', 'جيبوتي'), ('KM', 'جزر القمر'), ('US', 'الولايات المتحدة'), ('GB', 'المملكة المتحدة'), ('DE', 'ألمانيا'), ('FR', 'فرنسا'), ('CA', 'كندا'), ('AU', 'أستراليا'), ('CN', 'الصين'), ('JP', 'اليابان'), ('RU', 'روسيا'), ('IT', 'إيطاليا'), ('ES', 'إسبانيا'), ('CH', 'سويسرا'), ('NL', 'هولندا'), ('BE', 'بلجيكا'), ('SE', 'السويد'), ('NO', 'النرويج'), ('FI', 'فنلندا'), ('DK', 'الدنمارك'), ('AT', 'النمسا'), ('GR', 'اليونان'), ('CY', 'قبرص'), ('MY', 'ماليزيا'), ('ID', 'إندونيسيا'), ('IN', 'الهند'), ('PK', 'باكستان'), ('AF', 'أفغانستان'), ('IR', 'إيران'), ('AZ', 'أذربيجان'), ('GE', 'جورجيا'), ('UA', 'أوكرانيا'), ('PL', 'بولندا'), ('RO', 'رومانيا'), ('CZ', 'تشيكيا'), ('HU', 'المجر'), ('BR', 'البرازيل'), ('AR', 'الأرجنتين'), ('MX', 'المكسيك'), ('NG', 'نيجيريا'), ('ZA', 'جنوب أفريقيا')], default='', max_length=2, verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='مكان الميلاد'),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='selfie_verification',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfie/', verbose_name='صورة سيلفي مع الوثيقة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_full_name',
            field=models.BooleanField(default=True, verbose_name='عرض الاسم الكامل'),
        ),
    ]
