from django.urls import path
from apps.site import views, api_views

urlpatterns = [
    # User Dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/wallet/", views.wallet_page, name="dashboard_wallet"),
    path("dashboard/orders/", views.orders_list, name="dashboard_orders"),
    path("dashboard/orders/<uuid:pk>/", views.order_detail, name="dashboard_order_detail"),
    path("dashboard/deposits/", views.deposits, name="dashboard_deposits"),
    path("dashboard/withdrawals/", views.withdrawals, name="dashboard_withdrawals"),
    path("dashboard/notifications/settings/", views.notification_settings, name="notification_settings"),
    path("dashboard/change-password/", views.v3_change_password_view, name="change_password"),
    path("dashboard/change-email/", views.v3_change_email_view, name="change_email"),
    path("dashboard/2fa/setup/", views.v3_2fa_setup_view, name="site_2fa_setup"),
    path("dashboard/security-triggers/", views.v3_security_triggers_view, name="site_security_triggers"),
    path("auth/2fa-verify/", views.v3_2fa_verify_view, name="site_2fa_verify"),

    path("", views.home, name="home"),
    path("catalog/", views.catalog, name="catalog"),
    path("catalog/<uuid:pk>/", views.product_detail, name="product_detail"),
    
    # API Endpoints
    path("api/deposits/<uuid:pk>/approve/", api_views.api_deposit_approve, name="api_deposit_approve"),
    path("api/deposits/<uuid:pk>/reject/", api_views.api_deposit_reject, name="api_deposit_reject"),
    path("api/deposits/<uuid:pk>/correct/", api_views.api_deposit_correct, name="api_deposit_correct"),
    path("api/wallets/<uuid:pk>/hold/", api_views.api_wallet_hold, name="api_wallet_hold"),
    path("api/wallets/<uuid:pk>/unhold/", api_views.api_wallet_unhold, name="api_wallet_unhold"),
    path("api/withdrawals/<uuid:pk>/process/", api_views.api_withdrawal_process, name="api_withdrawal_process"),
    path("api/withdrawals/<uuid:pk>/approve/", api_views.api_withdrawal_approve, name="api_withdrawal_approve"),
    path("api/withdrawals/<uuid:pk>/complete/", api_views.api_withdrawal_complete, name="api_withdrawal_complete"),
    path("api/withdrawals/<uuid:pk>/reject/", api_views.api_withdrawal_reject, name="api_withdrawal_reject"),
    path("api/orders/<uuid:pk>/mark-read/", api_views.api_order_mark_read, name="api_order_mark_read"),

    # AUTHENTICATION (STANDARDIZED NAMES)
    path("auth/login/", views.v3_login_view, name="site_login"),
    path("auth/register/", views.v3_register_view, name="site_register"),
    path("auth/verify/", views.v3_verify_otp_view, name="site_verify_otp"),
    path("auth/forgot-password/", views.v3_forgot_password_view, name="site_forgot_password"),
    path("auth/reset-password/", views.v3_reset_password_view, name="site_reset_password"),
    path("auth/logout/", views.v3_logout_view, name="site_logout"),
    path("auth/resend-verification/", views.resend_verification, name="resend_verification"),
    path("auth/email-verify/<uidb64>/<token>/", views.email_verify, name="email_verify"),
    
    # KYC
    path("dashboard/verification/", views.kyc_request_view, name="site_kyc_request"),
    
    # Control Panel
    path("control/", views.control_dashboard, name="control_dashboard"),
    path("control/kyc/", views.control_kycs_list, name="control_kycs_list"),
    path("control/kyc/settings/", views.control_kyc_settings, name="control_kyc_settings"),
    path("control/kyc/<uuid:pk>/", views.control_kyc_detail, name="control_kyc_detail"),
    path("control/payment-methods/", views.payment_methods_list, name="payment_methods_list"),
    path("control/payment-methods/create/", views.payment_method_create, name="payment_method_create"),
    path("control/payment-methods/<uuid:pk>/edit/", views.payment_method_edit, name="payment_method_edit"),
    path("control/deposits/", views.control_deposits, name="control_deposits"),
    path("control/deposits/<uuid:pk>/", views.control_deposit_detail, name="control_deposit_detail"),
    path("control/withdrawals/", views.control_withdrawals, name="control_withdrawals"),
    path("control/withdrawals/<uuid:pk>/", views.control_withdrawal_detail, name="control_withdrawal_detail"),
    path("control/currencies/", views.currencies_list, name="currencies_list"),
    path("control/currencies/create/", views.currency_create, name="currency_create"),
    path("control/currencies/<uuid:pk>/edit/", views.currency_edit, name="currency_edit"),
    path("control/users/", views.control_users_list, name="control_users_list"),
    path("control/users/<uuid:public_uuid>/moderate/", views.control_user_moderate, name="control_user_moderate"),
    path("control/products/", views.control_products_list, name="control_products_list"),
    path("control/products/create/", views.control_product_create, name="control_product_create"),
    path("control/products/categories/create-ajax/", views.control_category_create_ajax, name="control_category_create_ajax"),
    path("control/products/<uuid:pk>/edit/", views.control_product_edit, name="control_product_edit"),
    path("control/products/<uuid:product_pk>/variants/create/", views.control_variant_create, name="control_variant_create"),
    path("control/variants/<uuid:pk>/edit/", views.control_variant_edit, name="control_variant_edit"),
    path("control/orders/", views.control_orders_list, name="control_orders_list"),
    path("control/orders/<uuid:pk>/", views.control_order_detail, name="control_order_detail"),
    path("control/coupons/", views.control_coupons_list, name="control_coupons_list"),
    path("control/coupons/create/", views.control_coupon_create, name="control_coupon_create"),
    path("control/coupons/<uuid:pk>/edit/", views.control_coupon_edit, name="control_coupon_edit"),
    path("control/coupons/<uuid:pk>/delete/", views.control_coupon_delete, name="control_coupon_delete"),
    path("control/wallets/", views.control_wallets_list, name="control_wallets_list"),
    path("control/debts/", views.control_debts, name="control_debts"),
    path("control/reports/", views.control_reports, name="control_reports"),
    path("control/support/settings/", views.control_support_settings, name="control_support_settings"),
    path("control/support/quick-replies/", views.control_quick_replies, name="control_quick_replies"),
    path("control/support/quick-replies/create/", views.control_quick_reply_create, name="control_quick_reply_create"),
    path("control/support/quick-replies/<uuid:pk>/edit/", views.control_quick_reply_edit, name="control_quick_reply_edit"),
    path("control/support/quick-replies/<uuid:pk>/delete/", views.control_quick_reply_delete, name="control_quick_reply_delete"),
    path("control/support/chat-open/", views.control_support_chat_open, name="control_support_chat_open"),
    path("control/announcements/", views.control_announcements, name="control_announcements"),
    path("control/announcements/create/", views.control_announcement_create, name="control_announcement_create"),
    path("control/announcements/<uuid:pk>/edit/", views.control_announcement_edit, name="control_announcement_edit"),
    path("control/announcements/<uuid:pk>/delete/", views.control_announcement_delete, name="control_announcement_delete"),
    path("control/settings/social-media/", views.control_social_media, name="control_social_media"),
    path("control/settings/social-media/<uuid:pk>/delete/", views.control_social_media_delete, name="control_social_media_delete"),
    path("control/notifications/send/", views.control_send_notification, name="control_send_notification"),

    # Legal & Support Pages
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("terms-of-service/", views.terms_of_service, name="terms_of_service"),
    path("refund-policy/", views.refund_policy, name="refund_policy"),
    path("contact/", views.contact_page, name="contact"),
    path("sw.js", views.service_worker, name="service_worker"),
    path("set-currency/", views.set_currency, name="set_currency"),
    path("ajax/validate-coupon/", views.ajax_validate_coupon, name="ajax_validate_coupon"),
]
