# Generated by Django 5.1.1 on 2026-06-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('bill_payment', 'دفع فواتير'), ('appointment', 'حجز موعد'), ('government', 'خدمات حكومية'), ('transfer', 'تحويل أموال'), ('mobile_topup', 'شحن رصيد'), ('custom', 'مخصص')], default='custom', max_length=40),
        ),
    ]
