# Generated by Django 5.1.1 on 2026-06-01 21:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='اسم الوسيلة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment-methods/logos/', verbose_name='الشعار')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة (FontAwesome)')),
                ('method_type', models.CharField(choices=[('bank', 'بنك'), ('wallet', 'محفظة إلكترونية'), ('crypto', 'عملات رقمية'), ('cash', 'نقدي'), ('mobile_payment', 'دفع عبر الهاتف')], max_length=40, verbose_name='نوع الوسيلة')),
                ('provider_name', models.CharField(blank=True, max_length=120, verbose_name='اسم المزود أو البنك')),
                ('description', models.TextField(blank=True, verbose_name='وصف الوسيلة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('account_number', models.CharField(blank=True, max_length=120, verbose_name='رقم الحساب')),
                ('account_name', models.CharField(blank=True, max_length=120, verbose_name='اسم صاحب الحساب')),
                ('iban', models.CharField(blank=True, max_length=120, verbose_name='IBAN')),
                ('wallet_address', models.CharField(blank=True, max_length=255, verbose_name='عنوان المحفظة / معرف')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='payment-methods/qr/', verbose_name='صورة QR')),
                ('instructions', models.TextField(blank=True, verbose_name='تعليمات الدفع')),
                ('custom_notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('min_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الحد الأدنى للإيداع')),
                ('max_deposit', models.DecimalField(decimal_places=2, default=Decimal('10000000.00'), max_digits=14, verbose_name='الحد الأقصى للإيداع')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='رسوم ثابتة')),
                ('percentage_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='رسوم مئوية (%)')),
                ('supported_currencies', models.JSONField(blank=True, default=list, verbose_name='العملات المدعومة')),
            ],
            options={
                'verbose_name': 'وسيلة دفع',
                'verbose_name_plural': 'وسائل الدفع',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='depositrequest',
            name='provider',
        ),
        migrations.AlterModelOptions(
            name='depositrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب إيداع', 'verbose_name_plural': 'طلبات الإيداع'},
        ),
        migrations.RemoveIndex(
            model_name='depositrequest',
            name='payments_de_externa_9d60ce_idx',
        ),
        migrations.RemoveField(
            model_name='depositrequest',
            name='external_reference',
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مبلغ الرسوم'),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ النهائي (الصافي)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=160, verbose_name='رقم العملية / المرجع'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='ملاحظات المدير'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='currency',
            field=models.CharField(default='SYP', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='customer_note',
            field=models.TextField(blank=True, verbose_name='ملاحظات العميل'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='deposit-proofs/', verbose_name='وصل الدفع'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deposits', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة من قبل'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('under_review', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='payment_method',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='payments.paymentmethod', verbose_name='وسيلة الدفع'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['transaction_id'], name='payments_de_transac_10a79b_idx'),
        ),
        migrations.DeleteModel(
            name='PaymentProvider',
        ),
    ]
