# Generated by Django 5.1.1 on 2026-06-01 21:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_remove_depositrequest_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='max_deposit',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='min_deposit',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='can_deposit',
            field=models.BooleanField(default=True, verbose_name='متاحة للإيداع'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='can_withdraw',
            field=models.BooleanField(default=False, verbose_name='متاحة للسحب'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000000.00'), max_digits=14, verbose_name='الحد الأقصى'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الحد الأدنى'),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المطلوب')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرسوم')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ الصافي للاستلام')),
                ('currency', models.CharField(default='SYP', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('payout_details', models.JSONField(default=dict, verbose_name='بيانات التحويل')),
                ('admin_note', models.TextField(blank=True, verbose_name='ملاحظات المدير')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='withdrawal-proofs/', verbose_name='إثبات التحويل')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='payments.paymentmethod', verbose_name='وسيلة السحب')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة من قبل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب سحب',
                'verbose_name_plural': 'طلبات السحب',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='payments_wi_user_id_c530c4_idx'), models.Index(fields=['status'], name='payments_wi_status_10ece7_idx')],
            },
        ),
    ]
