# Generated by Django 5.1.1 on 2026-06-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('payments', '0003_remove_paymentmethod_max_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='العملة'),
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='supported_currencies',
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='supported_currencies',
            field=models.ManyToManyField(blank=True, to='common.currency', verbose_name='العملات المدعومة'),
        ),
    ]
