# Generated by Django 5.1.1 on 2026-06-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_depositrequest_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('bank', 'بنك'), ('wallet', 'محفظة إلكترونية'), ('cash', 'نقدي'), ('mobile_payment', 'دفع عبر الهاتف')], max_length=40, verbose_name='نوع الوسيلة'),
        ),
    ]
