# Generated by Django 5.1.1 on 2026-06-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentmethod_method_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='form_schema',
            field=models.JSONField(blank=True, default=dict, help_text='مثال: {"version": 1, "fields": [{"label": "رقم الحوالة", "type": "text", "required": true}]}', verbose_name='نموذج البيانات الديناميكي'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم صاحب الحساب (افتراضي)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='رقم الحساب (افتراضي)'),
        ),
    ]
