# Generated by Django 5.1.1 on 2026-06-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentmethod_form_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='withdrawal_form_schema',
            field=models.JSONField(blank=True, default=dict, help_text='مثال: {"version": 1, "fields": [{"label": "رقم المحفظة", "type": "text", "required": true}]}', verbose_name='نموذج بيانات السحب (JSON)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='form_schema',
            field=models.JSONField(blank=True, default=dict, help_text='مثال: {"version": 1, "fields": [{"label": "رقم الحوالة", "type": "text", "required": true}]}', verbose_name='نموذج بيانات الإيداع (JSON)'),
        ),
    ]
