# Generated by Django 5.1.1 on 2026-06-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentmethod_withdrawal_form_schema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='custom_notes',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='fixed_fee',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='percentage_fee',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='deposit_fee_settings',
            field=models.JSONField(blank=True, default=dict, help_text='{"fixed": 0, "percent": 0, "min": 0, "max": 0, "enabled": true}', verbose_name='إعدادات رسوم الإيداع'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='deposit_info_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات الإيداع الثابتة (للعرض)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='withdrawal_fee_settings',
            field=models.JSONField(blank=True, default=dict, help_text='{"fixed": 0, "percent": 0, "min": 0, "max": 0, "enabled": true}', verbose_name='إعدادات رسوم السحب'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='withdrawal_info_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات السحب الثابتة (للعرض)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='form_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='حقول الإيداع المطلوبة من العميل'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات إضافية'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(max_length=100, verbose_name='نوع الوسيلة (مثلاً: بنك، محفظة)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='withdrawal_form_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='حقول السحب المطلوبة من العميل'),
        ),
    ]
