# Generated by Django 5.1.1 on 2026-06-05 12:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_paymentmethod_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=14, verbose_name='الحد الأقصى'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=14, verbose_name='الحد الأدنى'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='ترتيب العرض'),
        ),
    ]
