# Generated by Django 5.1.1 on 2026-06-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymentmethod_max_amount_paymentmethod_min_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='form_schema',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='deposit_form_schema',
            field=models.JSONField(blank=True, default=dict, help_text='{"version": 1, "fields": [{"label": "TXID", "type": "text", "required": true}]}', verbose_name='حقول الإيداع المطلوبة من العميل'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='deposit_info_schema',
            field=models.JSONField(blank=True, default=dict, help_text='{"version": 1, "rows": [{"title": "IBAN", "value": "TR...", "copyable": true}]}', verbose_name='بيانات الإيداع الثابتة (للعرض)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='withdrawal_form_schema',
            field=models.JSONField(blank=True, default=dict, help_text='{"version": 1, "fields": [{"label": "Binance UID", "type": "text", "required": true}]}', verbose_name='حقول السحب المطلوبة من العميل'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='withdrawal_info_schema',
            field=models.JSONField(blank=True, default=dict, help_text='{"version": 1, "rows": [{"title": "Processing Time", "value": "24h"}]}', verbose_name='بيانات السحب الثابتة (للعرض)'),
        ),
    ]
