# Generated by Django 5.1.1 on 2026-06-05 15:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_paymentmethod_form_schema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='deposit_instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات الإيداع'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='deposit_max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=14, verbose_name='الحد الأقصى للإيداع'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='deposit_min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=14, verbose_name='الحد الأدنى للإيداع'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='deposit_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment-methods/qr/', verbose_name='صورة QR للإيداع'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='withdrawal_instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات السحب'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='withdrawal_max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=14, verbose_name='الحد الأقصى للسحب'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='withdrawal_min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=14, verbose_name='الحد الأدنى للسحب'),
        ),
    ]
