# Generated by Django 5.1.1 on 2026-06-05 16:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_depositrequest_wallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='المبلغ بعملة المحفظة'),
        ),
    ]
