# Generated by Django 5.1.1 on 2026-06-05 22:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_withdrawalrequest_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='deposit_max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='القيمة بالدولار USD وسيتم تحويلها تلقائياً', max_digits=14, verbose_name='الحد الأقصى للإيداع'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='deposit_min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='القيمة بالدولار USD وسيتم تحويلها تلقائياً', max_digits=14, verbose_name='الحد الأدنى للإيداع'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='withdrawal_max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='القيمة بالدولار USD وسيتم تحويلها تلقائياً', max_digits=14, verbose_name='الحد الأقصى للسحب'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='withdrawal_min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='القيمة بالدولار USD وسيتم تحويلها تلقائياً', max_digits=14, verbose_name='الحد الأدنى للسحب'),
        ),
    ]
