# Generated by Django 5.1.1 on 2026-06-06 20:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_paymentmethod_deposit_max_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='daily_deposit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='القيمة بالدولار USD', max_digits=14, verbose_name='حد الإيداع اليومي لهذه الوسيلة'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='daily_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='القيمة بالدولار USD', max_digits=14, verbose_name='حد السحب اليومي لهذه الوسيلة'),
        ),
    ]
