# Generated by Django 5.1.1 on 2026-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_paymentmethod_daily_deposit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق'),
        ),
    ]
