# Generated by Django 5.1.1 on 2026-06-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_depositrequest_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='withdrawal-proofs/docs/', verbose_name='إثبات التحويل (ملف/PDF)'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='withdrawal-proofs/', verbose_name='إثبات التحويل (صورة)'),
        ),
    ]
