# Generated by Django 5.1.1 on 2026-06-12 19:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_withdrawalrequest_proof_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='capital_exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='سعر التكلفة الداخلي لهذه الوسيلة مقابل الدولار لحساب الأرباح الحقيقية.', max_digits=14, verbose_name='سعر صرف رأس المال الداخلي (التكلفة)'),
        ),
        migrations.CreateModel(
            name='PaymentMethodExchangeRateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_rate', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='السعر القديم')),
                ('new_rate', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='السعر الجديد')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rate_logs', to='payments.paymentmethod', verbose_name='وسيلة الدفع')),
            ],
            options={
                'verbose_name': 'سجل تعديل سعر الصرف',
                'verbose_name_plural': 'سجلات تعديل أسعار الصرف',
                'ordering': ['-created_at'],
            },
        ),
    ]
