# Generated by Django 5.1.1 on 2026-06-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_paymentmethod_capital_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='deposit_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='سعر صرف مخصص لعمليات الإيداع لهذه الوسيلة. إذا ترك فارغاً سيتم اعتماد السعر الافتراضي.', max_digits=14, null=True, verbose_name='سعر صرف الإيداع (التكلفة)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='withdrawal_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='سعر صرف مخصص لعمليات السحب لهذه الوسيلة. إذا ترك فارغاً سيتم اعتماد السعر الافتراضي.', max_digits=14, null=True, verbose_name='سعر صرف السحب (الربح)'),
        ),
    ]
