# Generated by Django 5.1.1 on 2026-06-13 22:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_paymentmethod_deposit_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='global_deposit_cap',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='عند الوصول لهذا الحد، تتوقف الوسيلة تلقائياً. 0 تعني غير محدود.', max_digits=14, verbose_name='الحد الإجمالي الأقصى للإيداعات'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='global_deposit_usage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي الإيداعات الحالية (للمتابعة والحد الأقصى)'),
        ),
    ]
