# Generated by Django 5.1.1 on 2026-06-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_paymentmethod_global_deposit_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='requires_kyc',
            field=models.BooleanField(default=False, help_text='إذا تم تفعيله، لن تظهر هذه الوسيلة إلا للمستخدمين الموثقين.', verbose_name='يتطلب توثيق الهوية (KYC)'),
        ),
    ]
