# Generated by Django 5.1.1 on 2026-06-13 23:45

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_paymentmethod_requires_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='daily_deposit_usage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='daily_withdrawal_usage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='last_limit_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
