# Generated by Django 5.1.1 on 2026-06-19 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_paymentmethod_global_withdrawal_cap_and_more'),
        ('stores', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to='stores.store', verbose_name='المتجر'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='stores.store', verbose_name='المتجر'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='stores.store', verbose_name='المتجر'),
        ),
    ]
