# Generated by Django 5.1.1 on 2026-06-24 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_currency_store_alter_currency_code_and_more'),
        ('payments', '0024_depositrequest_store_paymentmethod_store_and_more'),
        ('stores', '0008_store_display_order_store_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=160, null=True, verbose_name='رقم العملية / المرجع'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['transaction_id'], name='payments_wi_transac_6513df_idx'),
        ),
    ]
