# Generated by Django 5.1.1 on 2026-07-22 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_withdrawalrequest_transaction_id_and_more'),
        ('stores', '0008_store_display_order_store_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='اسم بوابة الدفع')),
                ('provider', models.CharField(choices=[('baniyas_crypto', 'Baniyas Crypto'), ('custom', 'Custom API')], default='baniyas_crypto', max_length=40, verbose_name='المزود')),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=20, verbose_name='وضع التشغيل')),
                ('base_url', models.URLField(blank=True, max_length=255, verbose_name='رابط API الأساسي')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API Secret')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook Secret')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشطة')),
                ('can_deposit', models.BooleanField(default=True, verbose_name='تدعم الإيداع')),
                ('can_withdraw', models.BooleanField(default=False, verbose_name='تدعم السحب')),
                ('supported_assets', models.JSONField(blank=True, default=list, verbose_name='الأصول المدعومة')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات إضافية')),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر فحص اتصال')),
                ('last_health_status', models.CharField(blank=True, max_length=30, verbose_name='نتيجة آخر فحص')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway_integrations', to='stores.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'بوابة دفع API',
                'verbose_name_plural': 'بوابات دفع API',
                'ordering': ['provider', 'name'],
            },
        ),
    ]
