# Generated by Django 5.1.1 on 2026-09-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_paymentgatewayintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='gateway_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='معرف دفعة البوابة'),
        ),
        migrations.AddField(
            model_name='paymentgatewayintegration',
            name='terminal_id',
            field=models.CharField(blank=True, help_text='المعرف المخصص من بيميرا والمؤلف من 8 خانات', max_length=64, verbose_name='رقم نقطة البيع (Terminal ID)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway',
            field=models.ForeignKey(blank=True, help_text='في حال تحديد بوابة دفع إلكترونية، سيتم توجيه العميل للدفع الإلكتروني التلقائي.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='payments.paymentgatewayintegration', verbose_name='بوابة الدفع الإلكترونية المرتبطة'),
        ),
        migrations.AlterField(
            model_name='paymentgatewayintegration',
            name='provider',
            field=models.CharField(choices=[('paymera', 'Paymera (بيميرا)'), ('baniyas_crypto', 'Baniyas Crypto'), ('custom', 'Custom API')], default='baniyas_crypto', max_length=40, verbose_name='المزود'),
        ),
    ]
