# Generated by Django 5.1.1 on 2026-09-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_seed_paymera_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayintegration',
            name='logo',
            field=models.ImageField(blank=True, help_text='الشعار الرسمي الذي يظهر للعملاء عند الدفع عبر هذه البوابة.', null=True, upload_to='payment-gateways/logos/', verbose_name='شعار البوابة'),
        ),
    ]
