# Generated by Django 5.1.1 on 2026-06-01 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='اسم العملة')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='رمز العملة (ISO)')),
                ('symbol', models.CharField(max_length=10, verbose_name='رمز العملة')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='نسبة الصرف مقابل العملة الأساسية (USD)', max_digits=14)),
                ('decimal_places', models.PositiveIntegerField(default=2, verbose_name='عدد الخانات العشرية')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='العملة الافتراضية')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
                'ordering': ['display_order', 'code'],
            },
        ),
    ]
