# Generated by Django 5.1.1 on 2026-06-04 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(max_length=100, verbose_name='نوع الإجراء')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('before_state', models.JSONField(blank=True, default=dict, verbose_name='الحالة قبل')),
                ('after_state', models.JSONField(blank=True, default=dict, verbose_name='الحالة بعد')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP عنوان')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المنفذ')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'سجل تدقيق النظام',
                'verbose_name_plural': 'سجلات تدقيق النظام',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type'], name='common_syst_action__c358f0_idx'), models.Index(fields=['content_type', 'object_id'], name='common_syst_content_7b22cf_idx')],
            },
        ),
    ]
