# Generated by Django 5.1.1 on 2026-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_systemauditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='buy_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='كم تساوي 1 وحدة من العملة الأساسية (مثال: 1 دولار = 10500 ليرة)', max_digits=14, verbose_name='سعر الشراء (للإيداع)'),
        ),
        migrations.AddField(
            model_name='currency',
            name='sell_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='كم تساوي 1 وحدة من العملة الأساسية (مثال: 1 دولار = 10000 ليرة)', max_digits=14, verbose_name='سعر المبيع (للسحب)'),
        ),
    ]
