# Generated by Django 5.1.1 on 2026-06-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_currency_exchange_rate_currency_buy_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='conversion_method',
            field=models.CharField(choices=[('multiply', 'ضرب (×)'), ('divide', 'قسمة (÷)')], default='multiply', max_length=10, verbose_name='طريقة التحويل'),
        ),
    ]
