# Generated by Django 5.1.1 on 2026-06-09 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_currency_conversion_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='اسم المنصة')),
                ('url', models.URLField(verbose_name='رابط الحساب')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='أيقونة/شعار')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class (e.g. fab fa-facebook)', max_length=50, verbose_name='كود الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'رابط تواصل اجتماعي',
                'verbose_name_plural': 'روابط التواصل الاجتماعي',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='systemauditlog',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveIndex(
            model_name='systemauditlog',
            name='common_syst_action__c358f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemauditlog',
            name='common_syst_content_7b22cf_idx',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='after_state',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='before_state',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='user_agent',
        ),
    ]
