# Generated by Django 5.1.1 on 2026-06-09 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_socialmedialink_alter_systemauditlog_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل تدقيق النظام', 'verbose_name_plural': 'سجلات تدقيق النظام'},
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='action_type',
            field=models.CharField(default=0, max_length=100, verbose_name='نوع الإجراء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المنفذ'),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='after_state',
            field=models.JSONField(blank=True, default=dict, verbose_name='الحالة بعد'),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='before_state',
            field=models.JSONField(blank=True, default=dict, verbose_name='الحالة قبل'),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP عنوان'),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='reason',
            field=models.TextField(blank=True, verbose_name='السبب'),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='متصفح المستخدم'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['action_type'], name='common_syst_action__c358f0_idx'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='common_syst_content_7b22cf_idx'),
        ),
    ]
