# Generated by Django 5.1.1 on 2026-06-11 00:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_systemauditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='نص الملاحظة')),
                ('link', models.URLField(blank=True, null=True, verbose_name='رابط (اختياري)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('background_color', models.CharField(default='#06b6d4', max_length=20, verbose_name='لون الخلفية')),
                ('text_color', models.CharField(default='#ffffff', max_length=20, verbose_name='لون النص')),
            ],
            options={
                'verbose_name': 'ملاحظة شريط الموقع',
                'verbose_name_plural': 'ملاحظات شريط الموقع',
            },
        ),
    ]
