# Generated by Django 5.1.1 on 2026-06-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_siteannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='capital_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='سعر التكلفة الحقيقي (الداخلي) مقابل الدولار لحساب الأرباح بدقة.', max_digits=14, verbose_name='سعر صرف التكلفة'),
        ),
    ]
