# Generated by Django 5.1.1 on 2026-06-16 23:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_currency_capital_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100, verbose_name='تسمية الإحصائية')),
                ('value_override', models.IntegerField(default=0, help_text='القيمة التي ستظهر (يتم إضافتها للرقم الحقيقي إن وجد)')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class (e.g. fas fa-users)', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'إحصائية المنصة',
                'verbose_name_plural': 'إحصائيات المنصة',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='التعليق/الشهادة')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='التقييم (1-5)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تمت الموافقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'شهادة عميل',
                'verbose_name_plural': 'شهادات العملاء',
            },
        ),
    ]
