# Generated by Django 5.1.1 on 2026-06-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_platformstatistic_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='رد الإدارة'),
        ),
    ]
