# Generated by Django 5.1.1 on 2026-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_testimonial_admin_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformstatistic',
            name='stat_type',
            field=models.CharField(choices=[('custom', 'مخصص'), ('users', 'المستخدمين'), ('orders', 'الطلبات'), ('deposits', 'الإيداعات'), ('withdrawals', 'السحوبات'), ('products', 'المنتجات'), ('execution_time', 'وقت التنفيذ')], default='custom', max_length=20, verbose_name='نوع الإحصائية'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='display_name_publicly',
            field=models.BooleanField(default=True, verbose_name='عرض الاسم للعامة'),
        ),
        migrations.AlterField(
            model_name='platformstatistic',
            name='value_override',
            field=models.IntegerField(default=0, help_text='القيمة التي ستظهر (أو الزيادة على الرقم الحقيقي)'),
        ),
    ]
