# Generated by Django 5.1.1 on 2026-06-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_platformstatistic_stat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformstatistic',
            name='string_value',
            field=models.CharField(blank=True, help_text='قيمة نصية مخصصة (تتجاوز الرقم، مثال: 24/7)', max_length=50),
        ),
        migrations.AddField(
            model_name='platformstatistic',
            name='value_suffix',
            field=models.CharField(blank=True, default='+', help_text='مثال: + أو %', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformstatistic',
            name='value_override',
            field=models.IntegerField(default=0, help_text='القيمة الرقمية (يتم إضافتها للرقم الحقيقي)'),
        ),
    ]
