# Generated by Django 5.1.1 on 2026-06-22 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_siteannouncement_store'),
        ('stores', '0006_alter_store_background_color_alter_store_card_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='stores.store', verbose_name='المتجر'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, verbose_name='رمز العملة (ISO)'),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('code', 'store')},
        ),
    ]
