# Generated by Django 5.1.1 on 2026-07-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_sitemaintenancemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemaintenancemode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
