# Generated by Django 5.1.1 on 2026-09-19 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_restore_and_fix_site_id'),
        ('stores', '0013_fix_substore_product_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPixelConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pixel_name', models.CharField(blank=True, default='بيكسل إعلانات ميتا', max_length=120, verbose_name='تسمية البيكسل الخاص بك')),
                ('pixel_id', models.CharField(blank=True, help_text='معرف بيكسل ميتا المكون من 15-16 رقماً من مدير أحداث فيسبوك/ميتا', max_length=50, verbose_name='معرّف البيكسل (Pixel ID)')),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل البيكسل')),
                ('track_pageviews', models.BooleanField(default=True, verbose_name='تتبع مشاهدة الصفحات (PageView)')),
                ('track_view_content', models.BooleanField(default=True, verbose_name='تتبع تصفح المنتجات (ViewContent)')),
                ('track_initiate_checkout', models.BooleanField(default=True, verbose_name='تتبع بدء الشراء وإضافة السلة (AddToCart / InitiateCheckout)')),
                ('track_purchases', models.BooleanField(default=True, verbose_name='تتبع عمليات الشراء المكتملة (Purchase)')),
                ('track_registrations', models.BooleanField(default=True, verbose_name='تتبع تسجيل الحسابات الجديدة (CompleteRegistration)')),
                ('conversions_api_token', models.TextField(blank=True, verbose_name='رمز وصول واجهة تحويلات ميتا (Conversions API Token)')),
                ('test_event_code', models.CharField(blank=True, max_length=50, verbose_name='رمز اختبار الأحداث (Test Event Code)')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_pixel_configurations', to='stores.store', verbose_name='المتجر')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_pixel_updates', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات بيكسل ميتا (Meta Pixel)',
                'verbose_name_plural': 'إعدادات بيكسل ميتا (Meta Pixel)',
            },
        ),
    ]
