# Generated by Django 5.1.1 on 2026-09-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_set_default_meta_pixel'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapixelconfiguration',
            name='ad_account_id',
            field=models.CharField(blank=True, help_text='معرف حساب إعلانات ميتا (مثال: act_1234567890 أو 1234567890)', max_length=60, verbose_name='معرّف حساب الإعلانات (Ad Account ID)'),
        ),
    ]
