# Generated by Django 5.1.1 on 2026-09-19 23:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_metapixelconfiguration_ad_account_id'),
        ('stores', '0013_fix_substore_product_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapixelconfiguration',
            name='cached_ads_count',
            field=models.IntegerField(default=0, verbose_name='عدد الإعلانات'),
        ),
        migrations.AddField(
            model_name='metapixelconfiguration',
            name='cached_adsets_count',
            field=models.IntegerField(default=0, verbose_name='عدد المجموعات الإعلانية'),
        ),
        migrations.AddField(
            model_name='metapixelconfiguration',
            name='cached_campaigns_count',
            field=models.IntegerField(default=0, verbose_name='عدد الحملات'),
        ),
        migrations.AddField(
            model_name='metapixelconfiguration',
            name='last_sync_error',
            field=models.TextField(blank=True, verbose_name='آخر رسالة خطأ من ميتا'),
        ),
        migrations.AddField(
            model_name='metapixelconfiguration',
            name='last_sync_status',
            field=models.CharField(default='idle', max_length=50, verbose_name='حالة المزامنة'),
        ),
        migrations.AddField(
            model_name='metapixelconfiguration',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة مع ميتا'),
        ),
        migrations.CreateModel(
            name='MetaCampaignSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_id', models.CharField(max_length=80, verbose_name='معرّف الحملة في ميتا')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحملة')),
                ('status', models.CharField(default='UNKNOWN', max_length=40, verbose_name='الحالة')),
                ('effective_status', models.CharField(default='UNKNOWN', max_length=40, verbose_name='الحالة الفعلية')),
                ('objective', models.CharField(blank=True, max_length=80, verbose_name='هدف الحملة')),
                ('daily_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الميزانية اليومية')),
                ('lifetime_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الميزانية الإجمالية')),
                ('spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='المصروف')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='مرات الظهور')),
                ('reach', models.PositiveIntegerField(default=0, verbose_name='الوصول')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='النقرات')),
                ('cpc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='تكلفة النقرة')),
                ('cpm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='تكلفة الألف ظهور')),
                ('ctr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='نسبة النقر CTR')),
                ('registrations', models.PositiveIntegerField(default=0, verbose_name='التسجيلات')),
                ('purchases', models.PositiveIntegerField(default=0, verbose_name='المشتريات')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='قيمة المبيعات')),
                ('cpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='تكلفة الشراء CPA')),
                ('roas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='العائد الإعلاني ROAS')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات الخام من ميتا')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ المزامنة')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_campaign_snapshots', to='stores.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'لقطة حملة إعلانية لميتا',
                'verbose_name_plural': 'لقطات حملات ميتا الإعلانية',
                'ordering': ('-spend', '-created_at'),
            },
        ),
    ]
