# Generated by Django 5.1.1 on 2026-10-07 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_metapixelconfiguration_cached_ads_count_and_more'),
        ('stores', '0013_fix_substore_product_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, verbose_name='رمز الميزة')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الميزة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='مفعلة وتظهر للعملاء')),
                ('category', models.CharField(default='عام', max_length=50, verbose_name='القسم')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='stores.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'مفتاح ميزة (Feature Flag)',
                'verbose_name_plural': 'مفاتيح ميزات الموقع (Feature Flags)',
                'ordering': ('category', 'name'),
                'unique_together': {('key', 'store')},
            },
        ),
    ]
