# Generated by Django 5.1.1 on 2026-07-22 16:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0027_productvariant_metadata'),
        ('orders', '0020_order_api_order_id_order_api_order_uuid'),
        ('stores', '0008_store_display_order_store_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(max_length=100, verbose_name='معرف التصنيف في المزود')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التصنيف')),
                ('parent_remote_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف الأب في المزود')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='providers.providercategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(unique=True)),
                ('remote_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('parameters_sent', models.JSONField(default=dict)),
                ('local_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_orders', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderOrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('provider_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='providers.providerorder')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(max_length=100, verbose_name='معرف المنتج في المزود')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('product_type', models.CharField(choices=[('package', 'Package'), ('amount', 'Amount'), ('fixed_quantities', 'Fixed Quantities'), ('category_only', 'Category Only')], default='package', max_length=50, verbose_name='نوع المنتج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط في المزود')),
                ('cost_price', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=14, verbose_name='سعر التكلفة من المزود')),
                ('local_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم المخصص')),
                ('local_description', models.TextField(blank=True, null=True, verbose_name='الوصف المخصص')),
                ('local_is_active', models.BooleanField(default=True, verbose_name='ظاهر في المتجر')),
                ('local_image', models.ImageField(blank=True, null=True, upload_to='provider_products/', verbose_name='الصورة المخصصة')),
                ('local_sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('local_seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('local_seo_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('qty_min', models.IntegerField(blank=True, null=True)),
                ('qty_max', models.IntegerField(blank=True, null=True)),
                ('qty_list', models.JSONField(blank=True, default=list)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='providers.providercategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('new_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('old_final_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_final_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='providers.providerproduct')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('margin_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'نسبة مئوية'), ('manual', 'سعر يدوي')], default='percentage', max_length=20)),
                ('margin_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('manual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('round_to_nearest', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='providers.providerproduct')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='providerorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_orders', to='providers.providerproduct'),
        ),
        migrations.CreateModel(
            name='ProviderMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_mapping', to='catalog.product')),
                ('local_variant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_mapping', to='catalog.productvariant')),
                ('provider_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='providers.providerproduct')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderProductParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('parameter_type', models.CharField(default='text', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='providers.providerproduct')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(max_length=50, verbose_name='اسم المزود')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('base_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='الرابط الأساسي')),
                ('api_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح الـ API')),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='العملة')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر مزامنة')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_profiles', to='stores.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'ملف تعريف المزود',
                'verbose_name_plural': 'ملفات تعريف المزودين',
            },
        ),
        migrations.AddField(
            model_name='providerproduct',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='providers.providerprofile'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='providers.providerprofile'),
        ),
        migrations.AddField(
            model_name='providercategory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='providers.providerprofile'),
        ),
        migrations.CreateModel(
            name='ProviderRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('payload', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='providers.providerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='providers.providerprofile')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.providerrequestlog')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderResponseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('is_success', models.BooleanField(default=False)),
                ('request_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='providers.providerrequestlog')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('products_created', models.IntegerField(default=0)),
                ('products_updated', models.IntegerField(default=0)),
                ('products_disabled', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='providers.providerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='providerproduct',
            unique_together={('profile', 'remote_id')},
        ),
        migrations.AlterUniqueTogether(
            name='providercategory',
            unique_together={('profile', 'remote_id')},
        ),
    ]
