# Generated by Django 5.1.1 on 2026-07-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerproduct',
            name='qty_max',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providerproduct',
            name='qty_min',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
