# Generated by Django 5.1.1 on 2026-07-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_alter_product_category'),
        ('providers', '0002_alter_providerproduct_qty_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermapping',
            name='local_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_mappings', to='catalog.product'),
        ),
    ]
