# Generated by Django 5.1.1 on 2026-07-23 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_providermapping_local_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_orders', to='providers.providerproduct'),
        ),
    ]
