# Generated by Django 5.1.1 on 2026-07-23 17:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_providerorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprice',
            name='dealer_margin_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10, verbose_name='ربح التجار'),
        ),
        migrations.AddField(
            model_name='providerprice',
            name='retail_margin_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='ربح المفرق'),
        ),
        migrations.AddField(
            model_name='providerprice',
            name='vip_margin_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='ربح VIP'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='default_dealer_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10, verbose_name='نسبة/مبلغ ربح التجار/الجملة (%)'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='default_margin_type',
            field=models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'نسبة مئوية')], default='percentage', max_length=20, verbose_name='نوع هامش الربح الافتراضي'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='default_retail_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='نسبة/مبلغ ربح المفرق (%)'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='default_vip_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='نسبة/مبلغ ربح VIP (%)'),
        ),
        migrations.AlterField(
            model_name='providerprice',
            name='margin_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10),
        ),
    ]
