# Generated by Django 5.1.1 on 2026-09-04 18:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_providerprice_dealer_margin_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorder',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='providerprice',
            name='manual_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='providerpricehistory',
            name='new_cost',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='providerpricehistory',
            name='new_final_price',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='providerpricehistory',
            name='old_cost',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='providerpricehistory',
            name='old_final_price',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='providerproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18, verbose_name='سعر التكلفة من المزود'),
        ),
    ]
