# Generated by Django 5.1.1 on 2026-09-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_alter_providerorder_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerproduct',
            name='last_provider_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر مزامنة'),
        ),
        migrations.AddField(
            model_name='providerproduct',
            name='provider_base_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='سعر الأساس من المزود'),
        ),
        migrations.AddField(
            model_name='providerproduct',
            name='provider_category_img',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='رابط صورة التصنيف'),
        ),
        migrations.AddField(
            model_name='providerproduct',
            name='provider_category_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='اسم التصنيف من المزود'),
        ),
        migrations.AddField(
            model_name='providerproduct',
            name='raw_params',
            field=models.JSONField(blank=True, default=list, verbose_name='معاملات المنتج'),
        ),
        migrations.AddField(
            model_name='providerproduct',
            name='raw_qty_values',
            field=models.JSONField(blank=True, null=True, verbose_name='بيانات الكميات الخام'),
        ),
        migrations.AddField(
            model_name='providerproduct',
            name='remote_parent_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='معرف الأب في المزود'),
        ),
        migrations.AddField(
            model_name='providerproduct',
            name='sync_status',
            field=models.CharField(default='synced', max_length=50, verbose_name='حالة المزامنة'),
        ),
    ]
