# Generated by Django 5.1.1 on 2026-09-28 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_providerproduct_last_provider_sync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAppRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(help_text='مثال: pubg, ببجي, jawaker, تيك توك', max_length=100, verbose_name='الكلمة الدلالية / الكلمة المفتاحية')),
                ('section', models.CharField(choices=[('قسم الألعاب', 'قسم الألعاب'), ('قسم الدردشة والتطبيقات', 'قسم الدردشة والتطبيقات'), ('قسم الأرصدة والاتصالات', 'قسم الأرصدة والاتصالات'), ('البطاقات الإلكترونية', 'البطاقات الإلكترونية'), ('خدمات التلفاز والبث', 'خدمات التلفاز والبث'), ('اشتراكات VPN', 'اشتراكات VPN'), ('الذكاء الاصطناعي', 'الذكاء الاصطناعي'), ('برامج وتصميم', 'برامج وتصميم'), ('السوشيال ميديا', 'السوشيال ميديا'), ('الأرقام والحسابات', 'الأرقام والحسابات')], max_length=100, verbose_name='القسم الرئيسي')),
                ('app_name', models.CharField(help_text='مثال: ببجي موبايل (PUBG Mobile)', max_length=150, verbose_name='اسم التطبيق أو اللعبة في المتجر')),
                ('priority', models.IntegerField(default=10, verbose_name='الأولوية (الأعلى يطبق أولاً)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'قاعدة تصنيف المزود',
                'verbose_name_plural': 'قواعد تصنيف المزود',
                'ordering': ['-priority', 'keyword'],
            },
        ),
    ]
