# Generated by Django 5.1.1 on 2026-06-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('pending', 'قيد المراجعة'), ('resolved', 'تم الحل'), ('closed', 'مغلقة')], default='open', max_length=20),
        ),
    ]
