# Generated by Django 5.1.1 on 2026-06-01 21:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cannedreply',
            options={'verbose_name': 'رد جاهز', 'verbose_name_plural': 'الردود الجاهزة'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-last_reply_at'], 'verbose_name': 'تذكرة دعم', 'verbose_name_plural': 'تذاكر الدعم'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'رسالة تذكرة', 'verbose_name_plural': 'رسائل التذاكر'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_read_by_staff',
            field=models.BooleanField(default=False, verbose_name='قرأها الموظف'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_read_by_user',
            field=models.BooleanField(default=True, verbose_name='قرأها المستخدم'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_reply_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخر رد'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tickets/attachments/', verbose_name='مرفق'),
        ),
        migrations.AlterField(
            model_name='cannedreply',
            name='body',
            field=models.TextField(verbose_name='نص الرد'),
        ),
        migrations.AlterField(
            model_name='cannedreply',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='cannedreply',
            name='title',
            field=models.CharField(max_length=120, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('answered', 'تم الرد'), ('waiting_user', 'في انتظار العميل'), ('closed', 'مغلق')], default='open', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=180, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.TextField(verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='التذكرة'),
        ),
    ]
