# Generated by Django 5.1.1 on 2026-06-04 20:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_cannedreply_options_alter_ticket_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CannedReply',
            new_name='ChatCannedReply',
        ),
        migrations.AlterModelOptions(
            name='chatcannedreply',
            options={'verbose_name': 'رد جاهز (محادثة)', 'verbose_name_plural': 'الردود الجاهزة (محادثة)'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-last_reply_at'], 'verbose_name': 'تذكرة دعم (قديم)', 'verbose_name_plural': 'تذاكر الدعم (قديم)'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'رسالة تذكرة (قديم)', 'verbose_name_plural': 'رسائل التذاكر (قديم)'},
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=180, verbose_name='الموضوع')),
                ('status', models.CharField(choices=[('waiting', 'في الانتظار'), ('assigned', 'تم التعيين'), ('in_progress', 'قيد المعالجة'), ('closed', 'مغلق'), ('reopened', 'تم إعادة الفتح')], default='waiting', max_length=20, verbose_name='الحالة')),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخر رسالة')),
                ('unread_user_count', models.PositiveIntegerField(default=0, verbose_name='غير مقروء (للمستخدم)')),
                ('unread_staff_count', models.PositiveIntegerField(default=0, verbose_name='غير مقروء (للموظف)')),
                ('staff_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية للموظفين')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'غرفة محادثة',
                'verbose_name_plural': 'غرف المحادثة',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, verbose_name='النص')),
                ('file', models.FileField(blank=True, null=True, upload_to='chats/files/%Y/%m/', verbose_name='ملف')),
                ('is_image', models.BooleanField(default=False)),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.chatroom', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'رسالة محادثة',
                'verbose_name_plural': 'رسائل المحادثة',
                'ordering': ['created_at'],
            },
        ),
    ]
