# Generated by Django 5.1.1 on 2026-06-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_rename_cannedreply_chatcannedreply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(default='مرحباً بك! كيف يمكننا مساعدتك اليوم؟', help_text='هذه الرسالة تظهر تلقائياً عند فتح محادثة جديدة', verbose_name='رسالة الترحيب التلقائية')),
            ],
            options={
                'verbose_name': 'إعدادات الدعم',
                'verbose_name_plural': 'إعدادات الدعم',
            },
        ),
    ]
