# Generated by Django 5.1.1 on 2026-06-11 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_supportsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
