# Generated by Django 5.1.1 on 2026-06-22 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_store_background_color_alter_store_card_style_and_more'),
        ('support', '0006_remove_ticketmessage_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='stores.store', verbose_name='المتجر'),
        ),
    ]
