STORE_LIMIT_FIELDS = [
    "max_products",
    "max_categories",
    "max_monthly_orders",
    "max_customers",
    "max_employees",
    "max_branches",
    "max_coupons",
    "max_images",
    "max_storage_mb",
    "max_bandwidth_gb",
    "max_domains",
    "max_api_keys",
    "max_pages",
]

STORE_FEATURE_FIELDS = [
    "custom_domain_enabled",
    "remove_branding_enabled",
    "multi_employee_enabled",
    "multi_branch_enabled",
    "coupons_enabled",
    "recharge_cards_enabled",
    "wallets_enabled",
    "advanced_reports_enabled",
    "live_stats_enabled",
    "export_excel_enabled",
    "export_pdf_enabled",
    "api_access_enabled",
    "webhooks_enabled",
    "mobile_app_enabled",
    "sms_notifications_enabled",
    "whatsapp_notifications_enabled",
    "email_marketing_enabled",
    "import_products_enabled",
    "export_products_enabled",
    "backup_enabled",
    "restore_enabled",
    "professional_templates_enabled",
    "custom_css_js_enabled",
    "multi_language_enabled",
    "multi_currency_enabled",
]

