# Generated by Django 5.1.1 on 2026-06-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('credit', 'إيداع'), ('debit', 'خصم'), ('freeze', 'تجميد'), ('release', 'فك تجميد'), ('refund', 'استرداد')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('refunded', 'مسترد')], default='completed', max_length=20),
        ),
    ]
