# Generated by Django 5.1.1 on 2026-06-01 21:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_ledgerentry_entry_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل حركة', 'verbose_name_plural': 'سجلات الحركة'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'محفظة', 'verbose_name_plural': 'المحافظ'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'عملية مالية', 'verbose_name_plural': 'العمليات المالية'},
        ),
        migrations.AddField(
            model_name='wallet',
            name='held_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد المحجوز (إداري/نزاعات)'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد المعلق (إيداعات قيد الانتظار)'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, help_text='Available balance after this operation', max_digits=14),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('credit', 'إيداع'), ('debit', 'خصم'), ('freeze', 'تجميد'), ('release', 'فك تجميد'), ('hold', 'حجز إداري'), ('unhold', 'فك حجز'), ('refund', 'استرداد'), ('pending_deposit', 'إيداع معلق'), ('pending_cancel', 'إلغاء إيداع معلق')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد المتاح'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='frozen_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد المجمد (سحوبات/طلبات)'),
        ),
    ]
