# Generated by Django 5.1.1 on 2026-06-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('wallets', '0003_alter_ledgerentry_options_alter_wallet_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallet',
            new_name='wallets_wal_currenc_1f8e7e_idx',
            old_name='wallets_wal_currenc_7dd088_idx',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='العملة'),
        ),
    ]
