# Generated by Django 5.1.1 on 2026-06-04 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_wallet_reserved_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for the transaction', max_length=255),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='source',
            field=models.CharField(blank=True, help_text='Source of the transaction (e.g. order, deposit, admin)', max_length=100),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('credit', 'إيداع'), ('debit', 'خصم'), ('freeze', 'تجميد'), ('release', 'فك تجميد'), ('hold', 'حجز إداري'), ('unhold', 'فك حجز'), ('reserve', 'حجز طلب'), ('unreserve', 'فك حجز طلب'), ('refund', 'استرداد'), ('pending_deposit', 'إيداع معلق'), ('pending_cancel', 'إلغاء إيداع معلق')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['source'], name='wallets_led_source_6a86cb_idx'),
        ),
    ]
