# Generated by Django 5.1.1 on 2026-06-06 16:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_currency_conversion_method'),
        ('wallets', '0006_ledgerentry_reason_ledgerentry_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='debt_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد المستحق (ديون)'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('credit', 'إيداع'), ('debit', 'خصم'), ('freeze', 'تجميد'), ('release', 'فك تجميد'), ('hold', 'حجز إداري'), ('unhold', 'فك حجز'), ('reserve', 'حجز طلب'), ('unreserve', 'فك حجز طلب'), ('refund', 'استرداد'), ('pending_deposit', 'إيداع معلق'), ('pending_cancel', 'إلغاء إيداع معلق'), ('debt_add', 'إضافة دين'), ('debt_payment', 'سداد دين')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('debt_balance__gte', 0)), name='debt_balance_non_negative'),
        ),
    ]
