# Generated by Django 5.1.1 on 2026-06-18 13:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_platformstatistic_string_value_and_more'),
        ('wallets', '0007_wallet_debt_balance_alter_ledgerentry_entry_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المحول')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='رسوم التحويل')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ الصافي للمستلم')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reference', models.CharField(blank=True, max_length=120, unique=True, verbose_name='الرقم المرجعي')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='العملة')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'تحويل رصيد',
                'verbose_name_plural': 'تحويلات الرصيد',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'created_at'], name='wallets_bal_sender__782b6f_idx'), models.Index(fields=['recipient', 'created_at'], name='wallets_bal_recipie_d70ac4_idx'), models.Index(fields=['reference'], name='wallets_bal_referen_b38de7_idx')],
            },
        ),
    ]
