# Generated by Django 5.1.1 on 2026-06-19 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_platformstatistic_string_value_and_more'),
        ('orders', '0017_coupon_valid_for_users_after'),
        ('wallets', '0008_balancetransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز الشحن')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الشحن')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('redeemed', 'تم استخدامه'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشحن')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recharge_cards', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='العملة')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_cards', to='orders.order', verbose_name='الطلب المرتبط')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_recharge_cards', to=settings.AUTH_USER_MODEL, verbose_name='شحن بواسطة')),
            ],
            options={
                'verbose_name': 'بطاقة شحن',
                'verbose_name_plural': 'بطاقات الشحن',
                'ordering': ['-created_at'],
            },
        ),
    ]
