# Generated by Django 5.1.1 on 2026-06-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_rechargecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='debt_is_withdrawable',
            field=models.BooleanField(default=False, verbose_name='الدين قابل للسحب'),
        ),
    ]
