# Generated by Django 5.1.1 on 2026-06-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_wallet_debt_is_withdrawable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('rejected', 'مرفوض'), ('suspended', 'معلقة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
