# Generated by Django 5.1.1 on 2026-06-22 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_store_background_color_alter_store_card_style_and_more'),
        ('wallets', '0011_alter_balancetransfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargecard',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recharge_cards', to='stores.store', verbose_name='المتجر'),
        ),
    ]
