# Generated by Django 5.1.1 on 2026-06-24 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_currency_store_alter_currency_code_and_more'),
        ('stores', '0008_store_display_order_store_is_featured'),
        ('wallets', '0012_rechargecard_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='stores.store', verbose_name='المتجر'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'store')},
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'store'], name='wallets_wal_user_id_8b971d_idx'),
        ),
    ]
