# Generated by Django 5.1.1 on 2026-06-19 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الباقة')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='السعر الشهري (USD)')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='السعر السنوي (USD)')),
                ('max_products', models.PositiveIntegerField(default=10, verbose_name='أقصى عدد منتجات')),
                ('max_employees', models.PositiveIntegerField(default=1, verbose_name='أقصى عدد موظفين')),
                ('max_monthly_orders', models.PositiveIntegerField(default=100, verbose_name='أقصى عدد طلبات شهرياً')),
                ('max_storage_mb', models.PositiveIntegerField(default=100, verbose_name='مساحة التخزين القصوى (ميغابايت)')),
                ('max_images', models.PositiveIntegerField(default=100, verbose_name='أقصى عدد صور')),
                ('max_branches', models.PositiveIntegerField(default=1, verbose_name='أقصى عدد فروع')),
                ('max_coupons', models.PositiveIntegerField(default=5, verbose_name='أقصى عدد كوبونات')),
                ('max_domains', models.PositiveIntegerField(default=1, verbose_name='أقصى عدد دومينات مخصصة')),
                ('custom_domain_enabled', models.BooleanField(default=False, verbose_name='دعم دومين مخصص')),
                ('remove_branding_enabled', models.BooleanField(default=False, verbose_name='إزالة شعار رقميات')),
                ('api_access_enabled', models.BooleanField(default=False, verbose_name='صلاحية الوصول للـ API')),
                ('advanced_reports_enabled', models.BooleanField(default=False, verbose_name='التقارير المتقدمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراكات',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='اسم المتجر')),
                ('description', models.TextField(blank=True, verbose_name='وصف المتجر')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='رابط المتجر الفرعي (Subdomain slug)')),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='النطاق المخصص')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/', verbose_name='شعار المتجر')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='stores/banners/', verbose_name='بانر المتجر')),
                ('subscription_status', models.CharField(choices=[('active', 'نشط'), ('trialing', 'فترة تجريبية'), ('unpaid', 'غير مدفوع'), ('cancelled', 'ملغى'), ('suspended', 'موقوف')], default='trialing', max_length=20, verbose_name='حالة الاشتراك')),
                ('subscription_start', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء الاشتراك')),
                ('subscription_end', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك')),
                ('primary_color', models.CharField(default='#06b6d4', max_length=7, verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(default='#0891b2', max_length=7, verbose_name='اللون الثانوي')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='لون الخلفية')),
                ('text_color', models.CharField(default='#0f172a', max_length=7, verbose_name='لون النص')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('social_facebook', models.CharField(blank=True, max_length=255, verbose_name='فيسبوك')),
                ('social_instagram', models.CharField(blank=True, max_length=255, verbose_name='إنستغرام')),
                ('social_twitter', models.CharField(blank=True, max_length=255, verbose_name='تويتر/إكس')),
                ('social_tiktok', models.CharField(blank=True, max_length=255, verbose_name='تيك توك')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='stores.subscriptionplan', verbose_name='خطة الاشتراك')),
            ],
            options={
                'verbose_name': 'متجر',
                'verbose_name_plural': 'المتاجر',
            },
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_json', models.JSONField(blank=True, default=dict, verbose_name='إعدادات إضافية')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'إعداد متجر',
                'verbose_name_plural': 'إعدادات المتاجر',
            },
        ),
        migrations.CreateModel(
            name='StoreEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'مالك المتجر'), ('manager', 'مدير'), ('sales', 'موظف مبيعات'), ('support', 'موظف دعم'), ('moderator', 'مشرف منتجات'), ('accountant', 'محاسب'), ('custom', 'صلاحيات مخصصة')], default='sales', max_length=32, verbose_name='الوظيفة')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='الصلاحيات المخصصة')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='stores.store', verbose_name='المتجر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_employments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'موظف متجر',
                'verbose_name_plural': 'موظفو المتاجر',
                'unique_together': {('store', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StorePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='عنوان الصفحة')),
                ('slug', models.SlugField(max_length=100, verbose_name='رابط الصفحة')),
                ('content', models.TextField(verbose_name='محتوى الصفحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='stores.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'صفحة متجر',
                'verbose_name_plural': 'صفحات المتاجر',
                'unique_together': {('store', 'slug')},
            },
        ),
    ]
