# Generated by Django 5.1.1 on 2026-06-19 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSAdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور إداري SaaS',
                'verbose_name_plural': 'الأدوار الإدارية SaaS',
            },
        ),
        migrations.CreateModel(
            name='SaaSGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='رقميات', max_length=100, verbose_name='اسم المنصة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='saas/logo/', verbose_name='شعار المنصة')),
                ('support_email', models.EmailField(default='support@raqamiyatapp.com', max_length=254, verbose_name='البريد الإلكتروني للدعم')),
                ('allowed_languages', models.JSONField(blank=True, default=list, verbose_name='اللغات المدعومة')),
                ('allowed_currencies', models.JSONField(blank=True, default=list, verbose_name='العملات المدعومة')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة عمولة المنصة (%)')),
                ('backup_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات النسخ الاحتياطي')),
            ],
            options={
                'verbose_name': 'إعداد عام SaaS',
                'verbose_name_plural': 'إعدادات عامة SaaS',
            },
        ),
        migrations.CreateModel(
            name='StoreTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/templates/', verbose_name='صورة القالب')),
                ('category', models.CharField(max_length=100, verbose_name='فئة القالب')),
                ('mobile_responsive', models.BooleanField(default=True, verbose_name='متوافق مع الجوال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قالب متجر',
                'verbose_name_plural': 'قوالب المتاجر',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='limit_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='تجاوز الحدود يدوياً'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='backup_enabled',
            field=models.BooleanField(default=False, verbose_name='النسخ الاحتياطي'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='coupons_enabled',
            field=models.BooleanField(default=True, verbose_name='إنشاء أكواد خصم'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_css_js_enabled',
            field=models.BooleanField(default=False, verbose_name='تخصيص CSS و JavaScript'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='email_marketing_enabled',
            field=models.BooleanField(default=False, verbose_name='البريد الإلكتروني التسويقي'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='export_excel_enabled',
            field=models.BooleanField(default=False, verbose_name='تصدير Excel'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='export_pdf_enabled',
            field=models.BooleanField(default=False, verbose_name='تصدير PDF'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='export_products_enabled',
            field=models.BooleanField(default=False, verbose_name='تصدير المنتجات'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='import_products_enabled',
            field=models.BooleanField(default=False, verbose_name='استيراد المنتجات'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='live_stats_enabled',
            field=models.BooleanField(default=False, verbose_name='إحصائيات مباشرة'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_api_keys',
            field=models.PositiveIntegerField(default=1, verbose_name='أقصى عدد مفاتيح API'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_bandwidth_gb',
            field=models.PositiveIntegerField(default=100, verbose_name='أقصى استهلاك للباندويث (جيغابايت)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_categories',
            field=models.PositiveIntegerField(default=10, verbose_name='أقصى عدد تصنيفات'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_customers',
            field=models.PositiveIntegerField(default=100, verbose_name='أقصى عدد عملاء'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_pages',
            field=models.PositiveIntegerField(default=5, verbose_name='أقصى عدد صفحات مخصصة'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='mobile_app_enabled',
            field=models.BooleanField(default=False, verbose_name='تطبيق جوال'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='multi_branch_enabled',
            field=models.BooleanField(default=False, verbose_name='دعم تعدد الفروع'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='multi_currency_enabled',
            field=models.BooleanField(default=False, verbose_name='دعم العملات المتعددة'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='multi_employee_enabled',
            field=models.BooleanField(default=False, verbose_name='دعم تعدد الموظفين'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='multi_language_enabled',
            field=models.BooleanField(default=False, verbose_name='دعم اللغات المتعددة'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='professional_templates_enabled',
            field=models.BooleanField(default=False, verbose_name='القوالب الاحترافية'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='recharge_cards_enabled',
            field=models.BooleanField(default=True, verbose_name='إنشاء بطاقات شحن'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='restore_enabled',
            field=models.BooleanField(default=False, verbose_name='استعادة النسخ الاحتياطية'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='إشعارات SMS'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=14, verbose_name='فترة تجريبية (أيام)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='wallets_enabled',
            field=models.BooleanField(default=True, verbose_name='إنشاء محافظ إلكترونية'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='webhooks_enabled',
            field=models.BooleanField(default=False, verbose_name='Webhooks'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='whatsapp_notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='إشعارات WhatsApp'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='advanced_reports_enabled',
            field=models.BooleanField(default=False, verbose_name='تقارير متقدمة'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='api_access_enabled',
            field=models.BooleanField(default=False, verbose_name='REST API'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='custom_domain_enabled',
            field=models.BooleanField(default=False, verbose_name='ربط دومين مخصص'),
        ),
        migrations.CreateModel(
            name='SaaSAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='العملية')),
                ('description', models.TextField(verbose_name='التفاصيل')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق SaaS',
                'verbose_name_plural': 'سجلات تدقيق SaaS',
                'ordering': ['-created_at'],
            },
        ),
    ]
