# Generated by Django 5.1.1 on 2026-06-19 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_platformstatistic_string_value_and_more'),
        ('stores', '0002_saasadminrole_saasglobalsetting_storetemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='button_color',
            field=models.CharField(default='#06b6d4', max_length=7, verbose_name='لون الأزرار'),
        ),
        migrations.AddField(
            model_name='store',
            name='card_style',
            field=models.CharField(default='flat', max_length=20, verbose_name='شكل البطاقات'),
        ),
        migrations.AddField(
            model_name='store',
            name='footer_style',
            field=models.CharField(default='classic', max_length=20, verbose_name='شكل الفوتر'),
        ),
        migrations.AddField(
            model_name='store',
            name='header_style',
            field=models.CharField(default='classic', max_length=20, verbose_name='شكل الهيدر'),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_font',
            field=models.CharField(default='Cairo', max_length=50, verbose_name='الخط'),
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='لون الخلفية'),
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='button_color',
            field=models.CharField(default='#06b6d4', max_length=7, verbose_name='لون الأزرار'),
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='card_style',
            field=models.CharField(default='flat', max_length=20, verbose_name='شكل البطاقات'),
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='footer_style',
            field=models.CharField(default='classic', max_length=20, verbose_name='شكل الفوتر'),
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='header_style',
            field=models.CharField(default='classic', max_length=20, verbose_name='شكل الهيدر'),
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='primary_color',
            field=models.CharField(default='#06b6d4', max_length=7, verbose_name='اللون الأساسي'),
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='secondary_color',
            field=models.CharField(default='#0891b2', max_length=7, verbose_name='اللون الثانوي'),
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='text_color',
            field=models.CharField(default='#0f172a', max_length=7, verbose_name='لون النص'),
        ),
        migrations.AddField(
            model_name='storetemplate',
            name='theme_font',
            field=models.CharField(default='Cairo', max_length=50, verbose_name='الخط'),
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('status', models.CharField(choices=[('paid', 'مدفوعة'), ('unpaid', 'غير مدفوعة'), ('refunded', 'مستردة')], default='paid', max_length=20, verbose_name='حالة الفاتورة')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='العملة')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.subscriptionplan', verbose_name='باقة الاشتراك')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_invoices', to='stores.store', verbose_name='المتجر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'فاتورة اشتراك',
                'verbose_name_plural': 'فواتير الاشتراكات',
                'ordering': ['-issued_at'],
            },
        ),
    ]
