# Generated by Django 5.1.1 on 2026-06-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_rename_store_slug_to_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='auto_renew',
            field=models.BooleanField(default=True, verbose_name='تجديد تلقائي للاشتراك'),
        ),
        migrations.AddField(
            model_name='store',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي')], default='monthly', max_length=20, verbose_name='دورة الدفع'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='yearly_discount_percentage',
            field=models.PositiveIntegerField(default=16, verbose_name='نسبة خصم الاشتراك السنوي (%)'),
        ),
    ]
