# Generated by Django 5.1.1 on 2026-06-22 20:06

from django.db import migrations, models

def update_existing_stores(apps, schema_editor):
    Store = apps.get_model('stores', 'Store')
    Store.objects.filter(background_color='#ffffff').update(
        background_color='#030712',
        text_color='#f8fafc',
        card_style='glass'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_auto_renew_store_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='background_color',
            field=models.CharField(default='#030712', max_length=7, verbose_name='لون الخلفية'),
        ),
        migrations.AlterField(
            model_name='store',
            name='card_style',
            field=models.CharField(default='glass', max_length=20, verbose_name='شكل البطاقات'),
        ),
        migrations.AlterField(
            model_name='store',
            name='text_color',
            field=models.CharField(default='#f8fafc', max_length=7, verbose_name='لون النص'),
        ),
        migrations.RunPython(update_existing_stores),
    ]
