# Generated by Django 5.1.1 on 2026-06-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_store_background_color_alter_store_card_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='button_style',
            field=models.CharField(default='pill', max_length=20, verbose_name='شكل الأزرار'),
        ),
        migrations.AddField(
            model_name='store',
            name='custom_css',
            field=models.TextField(blank=True, default='', verbose_name='كود CSS مخصص'),
        ),
        migrations.AddField(
            model_name='store',
            name='shadow_style',
            field=models.CharField(default='soft', max_length=20, verbose_name='قوة الظلال'),
        ),
    ]
