# Generated by Django 5.1.1 on 2026-06-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_button_style_store_custom_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='ترتيب الظهور'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='متجر مميز للترويج'),
        ),
    ]
