# Generated by Django 5.1.1 on 2026-09-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_display_order_store_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='import_products_from_raqamiyat',
            field=models.BooleanField(default=True, help_text='تفعيل استيراد ومزامنة منتجات وخدمات منصة رقميات في المتجر', verbose_name='استيراد منتجات من رقميات'),
        ),
    ]
