# Generated by Django 5.1.1 on 2026-09-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_import_products_from_raqamiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tier_margins',
            field=models.JSONField(blank=True, default=dict, help_text='مثال: {"customer": 15.0, "dealer": 10.0, "vip": 5.0}', verbose_name='نسب أرباح الفئات (%)'),
        ),
    ]
