# Generated by Django 5.1.1 on 2026-06-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(choices=[('automatic', 'تسليم تلقائي'), ('manual', 'تسليم يدوي'), ('api', 'تسليم عبر API'), ('custom_form', 'نموذج مخصص')], default='manual', max_length=30),
        ),
    ]
