# Generated by Django 5.1.1 on 2026-06-01 21:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_delivery_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('sort_order', 'price'), 'verbose_name': 'باقة منتج', 'verbose_name_plural': 'باقات المنتجات'},
        ),
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/covers/', verbose_name='صورة الغلاف'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(blank=True, max_length=80, verbose_name='أيقونة (FA)'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbs/', verbose_name='مصغرة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=80, verbose_name='الأيقونة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='اسم التصنيف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(choices=[('automatic', 'تسليم تلقائي'), ('manual', 'تسليم يدوي'), ('api', 'تسليم عبر API'), ('custom_form', 'نموذج مخصص')], default='manual', max_length=30, verbose_name='نوع التسليم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/', verbose_name='الصورة الأساسية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات الاستخدام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز (عرض في الرئيسية)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=160, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='خصم (%)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='estimated_delivery_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='وقت التسليم المتوقع (دقيقة)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=120, verbose_name='اسم الباقة'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=80, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product')),
            ],
            options={
                'verbose_name': 'صورة المنتج',
                'verbose_name_plural': 'معرض صور المنتج',
                'ordering': ('sort_order',),
            },
        ),
    ]
