# Generated by Django 5.1.1 on 2026-06-04 20:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='vip_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر VIP'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر الجملة'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الافتراضي (Retail)'),
        ),
        migrations.CreateModel(
            name='ProductTierPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(max_length=20, verbose_name='الفئة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_prices', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'سعر فئة',
                'verbose_name_plural': 'أسعار الفئات',
                'unique_together': {('variant', 'tier')},
            },
        ),
    ]
