# Generated by Django 5.1.1 on 2026-06-04 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productvariant_vip_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_type',
        ),
        migrations.AddField(
            model_name='product',
            name='form_schema',
            field=models.JSONField(blank=True, default=dict, help_text='مثال: {"version": 1, "fields": [{"label": "اسم المستخدم", "type": "text", "required": true}]}', verbose_name='نموذج البيانات المطلوبة من العميل'),
        ),
        migrations.CreateModel(
            name='ProductUserPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prices', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'سعر مخصص لمستخدم',
                'verbose_name_plural': 'أسعار مخصصة لمستخدمين',
                'unique_together': {('variant', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='ProductFormField',
        ),
    ]
