# Generated by Django 5.1.1 on 2026-06-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_slug_2b1eb6_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
