# Generated by Django 5.1.1 on 2026-06-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_product_catalog_pro_slug_2b1eb6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='icon',
        ),
    ]
