# Generated by Django 5.1.1 on 2026-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_time_display',
            field=models.CharField(blank=True, help_text='مثال: 5-15 دقيقة أو 1-2 ساعة', max_length=60, verbose_name='وقت التسليم المعروض'),
        ),
    ]
