# Generated by Django 5.1.1 on 2026-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_delivery_time_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_temporarily_disabled',
            field=models.BooleanField(default=False, verbose_name='إيقاف مؤقت (يظهر كغير متوفر)'),
        ),
    ]
