# Generated by Django 5.1.1 on 2026-06-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productvariant_is_temporarily_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='صورة التصنيف'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, verbose_name='غير متوفر (سيظل معروضاً)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='عليه عرض/تخفيض'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='عليه عرض خاص'),
        ),
    ]
