# Generated by Django 5.1.1 on 2026-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='تصنيف مميز (يظهر في الرئيسية)'),
        ),
    ]
