# Generated by Django 5.1.1 on 2026-06-19 12:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_category_is_featured'),
        ('common', '0012_platformstatistic_string_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_recharge_card',
            field=models.BooleanField(default=False, help_text='إذا تم التفعيل، سيتم توليد كود شحن تلقائياً عند اكتمال الطلب.', verbose_name='بطاقة شحن تلقائية'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='recharge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة كود الشحن التلقائي'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='recharge_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency', verbose_name='عملة كود الشحن التلقائي'),
        ),
    ]
