# Generated by Django 5.1.1 on 2026-06-19 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_productvariant_is_recharge_card_and_more'),
        ('orders', '0017_coupon_valid_for_users_after'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='delivery_type',
            field=models.CharField(choices=[('manual', 'تسليم يدوي'), ('keys', 'تسليم تلقائي (أكواد)')], default='manual', max_length=20, verbose_name='طريقة التسليم'),
        ),
        migrations.CreateModel(
            name='ProductKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_code', models.CharField(max_length=255, verbose_name='الكود')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keys', to='orders.order', verbose_name='الطلب')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_keys', to=settings.AUTH_USER_MODEL, verbose_name='المشتري')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='catalog.productvariant', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'مفتاح منتج',
                'verbose_name_plural': 'مفاتيح المنتجات',
                'ordering': ('-created_at',),
            },
        ),
    ]
