# Generated by Django 5.1.1 on 2026-06-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_productsuggestion_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital', 'منتج رقمي'), ('physical', 'منتج مادي')], default='digital', max_length=20, verbose_name='نوع المنتج'),
        ),
    ]
