# Generated by Django 5.1.1 on 2026-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/', verbose_name='الفيديو'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='الصورة'),
        ),
    ]
