# Generated by Django 5.1.1 on 2026-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_product_low_stock_threshold_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_api_product',
            field=models.BooleanField(default=False, verbose_name='منتج من الـ API'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='api_product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم المنتج في الـ API'),
        ),
    ]
