# Generated by Django 5.1.1 on 2026-07-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_product_is_api_product_productvariant_api_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='api_provider',
            field=models.CharField(blank=True, choices=[('alkasr', 'Alkasr VIP'), ('smm', 'SMM Provider'), ('other', 'مزوّد آخر')], default='alkasr', max_length=50, null=True, verbose_name='مزوّد الخدمة (API)'),
        ),
    ]
