# Generated by Django 5.1.1 on 2026-07-03 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_product_api_provider'),
        ('stores', '0008_store_display_order_store_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('alkasr', 'Alkasr VIP'), ('smm', 'SMM Provider'), ('other', 'Other API')], default='alkasr', max_length=20, verbose_name='نوع المزود')),
                ('name', models.CharField(max_length=100, verbose_name='اسم بوابة الربط')),
                ('base_url', models.URLField(max_length=255, verbose_name='رابط المزود (Base URL)')),
                ('api_token', models.CharField(max_length=255, verbose_name='مفتاح الوصول (API Token)')),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل الاتصال')),
                ('allow_sub_stores', models.BooleanField(default=True, verbose_name='السماح للمتاجر الفرعية بالاستخدام')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_integrations', to='stores.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'إعداد ربط API',
                'verbose_name_plural': 'إعدادات ربط API',
                'ordering': ('provider', 'name'),
            },
        ),
    ]
