# Generated by Django 5.1.1 on 2026-07-19 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_apiintegration'),
        ('stores', '0008_store_display_order_store_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='APITransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=50, verbose_name='المزود')),
                ('action', models.CharField(max_length=100, verbose_name='العملية')),
                ('product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المنتج في المزود')),
                ('order_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='المعرف الفريد للطلب')),
                ('request_url', models.TextField(verbose_name='رابط الطلب')),
                ('request_params', models.TextField(blank=True, null=True, verbose_name='معاملات الطلب')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='رمز استجابة HTTP')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='محتوى الاستجابة')),
                ('is_success', models.BooleanField(default=False, verbose_name='هل نجحت العملية؟')),
                ('error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز الخطأ')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='catalog.apiintegration', verbose_name='بوابة الربط')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_transactions', to='stores.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'سجل حركة API',
                'verbose_name_plural': 'سجلات حركات API',
                'ordering': ('-created_at',),
            },
        ),
    ]
