# Generated by Django 5.1.1 on 2026-07-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_apitransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
    ]
