# Generated by Django 5.1.1 on 2026-07-22 19:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_productvariant_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='السعر الافتراضي (Retail)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='vip_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='سعر VIP'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='سعر الجملة'),
        ),
    ]
