# Generated by Django 5.1.1 on 2026-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_apiintegration_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiintegration',
            name='provider',
            field=models.CharField(choices=[('alkasr', 'Alkasr VIP'), ('generic', 'مزوّد عام (Generic API)'), ('smm', 'مزوّد خدمات (SMM)'), ('other', 'مزوّد آخر')], default='generic', max_length=20, verbose_name='نوع المزود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='api_provider',
            field=models.CharField(blank=True, choices=[('alkasr', 'Alkasr VIP'), ('generic', 'مزوّد عام (Generic API)'), ('smm', 'مزوّد خدمات (SMM)'), ('other', 'مزوّد آخر')], default='generic', max_length=50, null=True, verbose_name='مزوّد الخدمة (API)'),
        ),
    ]
