# Generated by Django 5.1.1 on 2026-09-04 18:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_consolidate_and_clean_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiintegration',
            name='provider',
            field=models.CharField(choices=[('alkasr', 'رقميات'), ('tafa3olcard', 'تفاعل كارد (Tafa3ol Card)'), ('generic', 'مزوّد عام (Generic API)'), ('smm', 'مزوّد خدمات (SMM)'), ('other', 'مزوّد آخر')], default='generic', max_length=20, verbose_name='نوع المزود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='api_provider',
            field=models.CharField(blank=True, choices=[('alkasr', 'الكاسر VIP'), ('tafa3olcard', 'تفاعل كارد (Tafa3ol Card)'), ('generic', 'مزوّد عام (Generic API)'), ('smm', 'مزوّد خدمات (SMM)'), ('other', 'مزوّد آخر')], default='generic', max_length=50, null=True, verbose_name='مزوّد الخدمة (API)'),
        ),
        migrations.AlterField(
            model_name='producttierprice',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=18, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='productuserprice',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18, verbose_name='السعر الأساسي'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='vip_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18, verbose_name='سعر VIP'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18, verbose_name='سعر الجملة'),
        ),
    ]
