# Generated by Django 5.1.1 on 2026-09-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_fix_bobo_and_duration_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiintegration',
            name='provider',
            field=models.CharField(choices=[('raqamiyat', 'بوابة رقميات (Raqamiyat Platform)'), ('alkasr', 'الكاسر VIP (Alkasr VIP)'), ('tafa3olcard', 'تفاعل كارد (Tafa3ol Card)'), ('generic', 'مزوّد عام (Generic API)'), ('smm', 'مزوّد خدمات (SMM)'), ('other', 'مزوّد آخر')], default='generic', max_length=20, verbose_name='نوع المزود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='api_provider',
            field=models.CharField(blank=True, choices=[('raqamiyat', 'بوابة رقميات (Raqamiyat Platform)'), ('alkasr', 'الكاسر VIP'), ('tafa3olcard', 'تفاعل كارد (Tafa3ol Card)'), ('generic', 'مزوّد عام (Generic API)'), ('smm', 'مزوّد خدمات (SMM)'), ('other', 'مزوّد آخر')], default='generic', max_length=50, null=True, verbose_name='مزوّد الخدمة (API)'),
        ),
    ]
