# Generated by Django 5.1.1 on 2026-09-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_fix_variant_metadata_and_qty_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('price', 'sort_order', 'id'), 'verbose_name': 'باقة منتج', 'verbose_name_plural': 'باقات المنتجات'},
        ),
        migrations.AddField(
            model_name='product',
            name='api_product_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='رقم المنتج الرئيسي في الـ API'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider_parent_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='معرف الأب في المزود'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='provider_parent_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='معرف الأب في المزود'),
        ),
    ]
