# Generated by Django 5.1.1 on 2026-06-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'داخل التطبيق'), ('email', 'البريد الإلكتروني'), ('sms', 'SMS')], default='in_app', max_length=20),
        ),
    ]
