# Generated by Django 5.1.1 on 2026-06-05 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_notification_action_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة'),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_replies', models.BooleanField(default=True, verbose_name='ردود الدعم')),
                ('order_updates', models.BooleanField(default=True, verbose_name='تحديثات الطلبات')),
                ('financial_updates', models.BooleanField(default=True, verbose_name='العمليات المالية')),
                ('system_announcements', models.BooleanField(default=True, verbose_name='إعلانات النظام')),
                ('push_token', models.TextField(blank=True, help_text='Browser push registration token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعدادات التنبيهات',
                'verbose_name_plural': 'إعدادات التنبيهات',
            },
        ),
    ]
