# Generated by Django 5.1.1 on 2026-06-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='browser',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.TextField(),
        ),
    ]
