# Generated by Django 5.1.1 on 2026-06-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_pushsubscription_auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='financial_updates',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='order_updates',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='push_token',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='support_replies',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='system_announcements',
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_financial',
            field=models.BooleanField(default=True, verbose_name='العمليات المالية (داخل التطبيق)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_orders',
            field=models.BooleanField(default=True, verbose_name='تحديثات الطلبات (داخل التطبيق)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_promotions',
            field=models.BooleanField(default=True, verbose_name='العروض والترويج (داخل التطبيق)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_support',
            field=models.BooleanField(default=True, verbose_name='ردود الدعم (داخل التطبيق)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='push_financial',
            field=models.BooleanField(default=True, verbose_name='العمليات المالية (Push)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='push_orders',
            field=models.BooleanField(default=True, verbose_name='تحديثات الطلبات (Push)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='push_promotions',
            field=models.BooleanField(default=False, verbose_name='العروض والترويج (Push)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='push_support',
            field=models.BooleanField(default=True, verbose_name='ردود الدعم (Push)'),
        ),
    ]
