# Generated by Django 5.1.1 on 2026-06-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_notificationsetting_financial_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='email_financial',
            field=models.BooleanField(default=True, verbose_name='العمليات المالية (البريد)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='email_orders',
            field=models.BooleanField(default=True, verbose_name='تحديثات الطلبات (البريد)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='email_promotions',
            field=models.BooleanField(default=True, verbose_name='العروض والترويج (البريد)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='email_support',
            field=models.BooleanField(default=True, verbose_name='ردود الدعم (البريد)'),
        ),
    ]
