# Generated by Django 5.1.1 on 2026-06-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notificationsetting_email_financial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='admin_email_notifications',
            field=models.BooleanField(default=True, verbose_name='استلام إشعارات الإدارة عبر البريد'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='admin_new_deposit',
            field=models.BooleanField(default=True, verbose_name='طلبات إيداع جديدة'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='admin_new_kyc',
            field=models.BooleanField(default=True, verbose_name='طلبات توثيق جديدة'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='admin_new_order',
            field=models.BooleanField(default=True, verbose_name='طلبات شراء جديدة'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='admin_new_support',
            field=models.BooleanField(default=True, verbose_name='تذاكر دعم جديدة'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='admin_new_withdrawal',
            field=models.BooleanField(default=True, verbose_name='طلبات سحب جديدة'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='email_kyc',
            field=models.BooleanField(default=True, verbose_name='تحديثات التوثيق (البريد)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_kyc',
            field=models.BooleanField(default=True, verbose_name='تحديثات التوثيق (داخل التطبيق)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الإشعارات بشكل عام'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='push_kyc',
            field=models.BooleanField(default=True, verbose_name='تحديثات التوثيق (Push)'),
        ),
    ]
