# Generated by Django 5.1.1 on 2026-07-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notificationsetting_admin_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='admin_provider_alert',
            field=models.BooleanField(default=True, verbose_name='تنبيهات مشاكل مزودي الخدمة'),
        ),
    ]
